import type { Locale } from "@/lib/i18n";

type ModelFileCopy = {
  metadataTitle: string; metadataDescription: string; eyebrow: string; title: string; body: string;
  warning: string; status: string; fieldsTitle: string; risksTitle: string; sourcesTitle: string;
  fields: Array<{ title: string; body: string }>;
  risks: Array<{ title: string; body: string }>;
  sources: string[]; back: string; email: string;
};

const commonFields = {
  en: [
    { title: "Legal entity", body: "Example Infrastructure SPV Ltd — fictional entity used only for this template." },
    { title: "Current capital ask", body: "USD 25 million, stated 6 August 2026, for the construction phase." },
    { title: "Proposed instrument", body: "Senior secured project debt, subject to lender diligence and final terms." },
    { title: "Rights status", body: "Site-control agreement and principal permits recorded, with validity dates and conditions listed in the controlled file." },
    { title: "Project stage", body: "Detailed design complete; procurement and financial close remain outstanding." },
    { title: "Use of funds", body: "Construction, equipment, owner’s costs, contingency and financing costs, shown separately." },
    { title: "Sponsor contribution", body: "USD 5 million proposed equity contribution; evidence remains subject to controlled review." },
    { title: "Revenue model", body: "Contracted service payments under a draft 15-year agreement; execution remains a condition precedent." },
    { title: "Timetable", body: "Target financial close within six months and construction over 18 months; both are planning assumptions." },
  ],
};

const copy: Record<Locale, ModelFileCopy> = {
  en: { metadataTitle: "Illustrative model file — DESCO Compass", metadataDescription: "A fictional worked example showing the public fields and risks required by the Compass Disclosure Standard.", eyebrow: "Worked disclosure example", title: "What a screening-ready public file should contain.", body: "This fictional example demonstrates format and disclosure depth. It is not a real project, issuer, offer, recommendation or performance claim.", warning: "Illustrative template only. Every name, amount, date and project fact below is fictional and must not be used for an investment decision.", status: "Illustrative result: threshold met — 9/9 public fields and 5/5 risk categories, subject to genuine source evidence in a real file.", fieldsTitle: "Public screening fields", risksTitle: "Principal risk disclosure", sourcesTitle: "Source register", fields: commonFields.en, risks: [{ title: "Legal and rights", body: "Permit validity, site control and enforceability require independent legal confirmation." }, { title: "Technical", body: "Design integration, contractor capability and performance assumptions require technical diligence." }, { title: "Financial", body: "Cost escalation, debt terms, foreign exchange and funding availability may change project economics." }, { title: "Market and counterparty", body: "The draft revenue contract is not executed; demand and counterparty credit remain open." }, { title: "Execution and ESG", body: "Schedule, procurement, safeguards, community engagement and grievance controls require verified implementation plans." }], sources: ["Corporate and ownership records — illustrative source dated 1 August 2026", "Rights and permit register — illustrative source dated 2 August 2026", "Technical design report — illustrative source dated 3 August 2026", "Financial model and uses of funds — illustrative source dated 4 August 2026", "ESG and community plan — illustrative source dated 5 August 2026"], back: "Return to the sponsor pathway", email: "Email DESCO about project preparation" },
  fr: { metadataTitle: "Dossier modèle illustratif — DESCO Compass", metadataDescription: "Exemple fictif des champs publics et risques exigés par la norme Compass.", eyebrow: "Exemple de divulgation", title: "Contenu attendu d’un dossier public prêt pour la présélection.", body: "Cet exemple fictif montre le format et le niveau de divulgation. Il ne s’agit ni d’un projet réel, ni d’un émetteur, ni d’une offre, ni d’une recommandation.", warning: "Modèle illustratif uniquement. Tous les noms, montants, dates et faits ci-dessous sont fictifs.", status: "Résultat illustratif : seuil atteint — 9/9 champs publics et 5/5 catégories de risques, sous réserve de preuves réelles dans un dossier effectif.", fieldsTitle: "Champs de présélection publics", risksTitle: "Principaux risques", sourcesTitle: "Registre des sources", fields: [
    { title: "Entité juridique", body: "Example Infrastructure SPV Ltd — entité fictive utilisée uniquement pour ce modèle." }, { title: "Besoin actuel en capital", body: "25 millions USD, daté du 6 août 2026, pour la phase de construction." }, { title: "Instrument proposé", body: "Dette de projet senior garantie, sous réserve de la diligence et des conditions finales." }, { title: "Statut des droits", body: "Accord de contrôle du site et principaux permis enregistrés, avec leurs dates et conditions." }, { title: "Stade du projet", body: "Conception détaillée achevée ; achats et clôture financière restent à réaliser." }, { title: "Utilisation des fonds", body: "Construction, équipements, coûts du maître d’ouvrage, contingence et frais de financement séparés." }, { title: "Apport du porteur", body: "Apport proposé de 5 millions USD ; preuve soumise à examen contrôlé." }, { title: "Modèle de revenus", body: "Paiements contractuels sur 15 ans ; la signature reste une condition préalable." }, { title: "Calendrier", body: "Clôture visée sous six mois et construction sur 18 mois ; il s’agit d’hypothèses de planification." },
  ], risks: [{ title: "Juridique et droits", body: "La validité des permis, les droits sur le site et leur opposabilité exigent une confirmation juridique indépendante." }, { title: "Technique", body: "La conception, les entreprises et les hypothèses de performance exigent une diligence technique." }, { title: "Financier", body: "Les coûts, les conditions de dette, le change et le financement peuvent modifier l’économie du projet." }, { title: "Marché et contrepartie", body: "Le contrat de revenus n’est pas signé ; la demande et le crédit de la contrepartie restent à confirmer." }, { title: "Exécution et ESG", body: "Le calendrier, les achats, les garanties et la concertation exigent des plans vérifiés." }], sources: ["Documents de l’entité — source illustrative du 1 août 2026", "Registre des droits et permis — source illustrative du 2 août 2026", "Rapport technique — source illustrative du 3 août 2026", "Modèle financier — source illustrative du 4 août 2026", "Plan ESG et communautaire — source illustrative du 5 août 2026"], back: "Retour au parcours porteur", email: "Écrire à DESCO sur la préparation" },
  es: null as never, pt: null as never, zh: null as never,
};

copy.es = { ...copy.en, metadataTitle: "Expediente modelo ilustrativo — DESCO Compass", metadataDescription: "Ejemplo ficticio de los campos y riesgos exigidos por la Norma Compass.", eyebrow: "Ejemplo de divulgación", title: "Qué debe contener un expediente público listo para evaluación.", body: "Este ejemplo ficticio muestra el formato y la profundidad de divulgación. No es un proyecto, emisor, oferta o recomendación real.", warning: "Plantilla ilustrativa. Todos los nombres, importes, fechas y hechos son ficticios.", status: "Resultado ilustrativo: umbral cumplido — 9/9 campos y 5/5 riesgos, sujeto a evidencia real.", fieldsTitle: "Campos públicos", risksTitle: "Riesgos principales", sourcesTitle: "Registro de fuentes", fields: commonFields.en.map((x, i) => ({ title: ["Entidad jurídica", "Necesidad actual de capital", "Instrumento propuesto", "Estado de los derechos", "Etapa del proyecto", "Uso de fondos", "Aportación del promotor", "Modelo de ingresos", "Calendario"][i], body: ["Entidad ficticia usada solo para esta plantilla.", "25 millones USD, con fecha 6 de agosto de 2026, para construcción.", "Deuda sénior garantizada, sujeta a diligencia y condiciones finales.", "Control del sitio y permisos registrados con fechas y condiciones.", "Diseño detallado completo; quedan compras y cierre financiero.", "Construcción, equipos, costes del propietario, contingencia y financiación.", "Aportación propuesta de 5 millones USD, sujeta a revisión.", "Pagos de servicios durante 15 años; el contrato aún debe firmarse.", "Cierre previsto en seis meses y construcción en 18; son supuestos de planificación."][i] })), risks: commonFields.en.slice(0, 5).map((_, i) => ({ title: ["Legal y derechos", "Técnico", "Financiero", "Mercado y contraparte", "Ejecución y ESG"][i], body: ["Permisos y derechos requieren confirmación jurídica independiente.", "Diseño y rendimiento requieren diligencia técnica.", "Costes, deuda, divisas y financiación pueden cambiar la economía.", "El contrato no está firmado; demanda y crédito siguen abiertos.", "Calendario, compras, salvaguardas y comunidad requieren planes verificados."][i] })), sources: ["Registros corporativos — fuente ilustrativa del 1 de agosto de 2026", "Derechos y permisos — 2 de agosto de 2026", "Informe técnico — 3 de agosto de 2026", "Modelo financiero — 4 de agosto de 2026", "Plan ESG — 5 de agosto de 2026"], back: "Volver al recorrido del promotor", email: "Escribir a DESCO sobre la preparación" };
copy.pt = { ...copy.en, metadataTitle: "Dossiê modelo ilustrativo — DESCO Compass", metadataDescription: "Exemplo fictício dos campos e riscos exigidos pela Norma Compass.", eyebrow: "Exemplo de divulgação", title: "O que um dossiê público pronto para análise deve conter.", body: "Este exemplo fictício mostra o formato e a profundidade da divulgação. Não é um projeto, emitente, oferta ou recomendação real.", warning: "Modelo ilustrativo. Todos os nomes, valores, datas e factos são fictícios.", status: "Resultado ilustrativo: limiar cumprido — 9/9 campos e 5/5 riscos, sujeito a evidência real.", fieldsTitle: "Campos públicos", risksTitle: "Riscos principais", sourcesTitle: "Registo de fontes", fields: commonFields.en.map((x, i) => ({ title: ["Entidade jurídica", "Necessidade atual de capital", "Instrumento proposto", "Estado dos direitos", "Fase do projeto", "Utilização dos fundos", "Contribuição do promotor", "Modelo de receitas", "Calendário"][i], body: ["Entidade fictícia usada apenas neste modelo.", "25 milhões USD, datados de 6 de agosto de 2026, para construção.", "Dívida sénior garantida, sujeita a diligência e termos finais.", "Controlo do local e licenças registados com datas e condições.", "Projeto detalhado concluído; faltam aquisições e fecho financeiro.", "Construção, equipamento, custos do dono, contingência e financiamento.", "Contribuição proposta de 5 milhões USD, sujeita a análise.", "Pagamentos de serviços durante 15 anos; o contrato ainda será assinado.", "Fecho previsto em seis meses e construção em 18; são pressupostos de planeamento."][i] })), risks: commonFields.en.slice(0, 5).map((_, i) => ({ title: ["Jurídico e direitos", "Técnico", "Financeiro", "Mercado e contraparte", "Execução e ESG"][i], body: ["Licenças e direitos exigem confirmação jurídica independente.", "Projeto e desempenho exigem diligência técnica.", "Custos, dívida, câmbio e financiamento podem alterar a economia.", "O contrato não está assinado; procura e crédito continuam em aberto.", "Calendário, compras, salvaguardas e comunidade exigem planos verificados."][i] })), sources: ["Registos societários — fonte ilustrativa de 1 de agosto de 2026", "Direitos e licenças — 2 de agosto de 2026", "Relatório técnico — 3 de agosto de 2026", "Modelo financeiro — 4 de agosto de 2026", "Plano ESG — 5 de agosto de 2026"], back: "Voltar ao percurso do promotor", email: "Escrever à DESCO sobre a preparação" };
copy.zh = { ...copy.en, metadataTitle: "说明性示例档案 — DESCO Compass", metadataDescription: "展示 Compass 标准所需公开字段和风险的虚构示例。", eyebrow: "披露示例", title: "可进入筛选的公开档案应包含哪些内容。", body: "本虚构示例仅展示格式和披露深度，不是真实项目、发行方、要约或建议。", warning: "仅供说明。以下所有名称、金额、日期和项目事实均为虚构。", status: "说明性结果：达到门槛，即 9/9 个公开字段和 5/5 个风险类别；真实档案仍须提供实际来源证据。", fieldsTitle: "公开筛选字段", risksTitle: "主要风险披露", sourcesTitle: "来源登记", fields: commonFields.en.map((x, i) => ({ title: ["法律实体", "当前融资需求", "拟议工具", "权利状态", "项目阶段", "资金用途", "发起方投入", "收入模式", "时间表"][i], body: ["仅用于本模板的虚构实体。", "截至 2026 年 8 月 6 日，建设阶段需要 2500 万美元。", "高级担保项目债务，须经贷款方尽调并确定最终条款。", "场地控制和主要许可已登记，并列明有效期及条件。", "详细设计已完成；采购和财务交割尚未完成。", "建设、设备、业主成本、预备费及融资成本分别列示。", "拟投入 500 万美元股本，证据须接受受控审查。", "依据拟定的 15 年服务协议收取款项；签署仍是先决条件。", "目标六个月内完成财务交割，建设期 18 个月；均为规划假设。 "][i] })), risks: commonFields.en.slice(0, 5).map((_, i) => ({ title: ["法律与权利", "技术", "财务", "市场与交易对手", "执行与 ESG"][i], body: ["许可、场地权利及可执行性须经独立法律确认。", "设计、承包商能力及性能假设须经技术尽调。", "成本、债务条款、汇率和资金可得性可能改变项目经济性。", "收入合同尚未签署，需求及交易对手信用仍待确认。", "进度、采购、保障措施及社区参与须有经核验的实施计划。 "][i] })), sources: ["公司及所有权记录 — 说明性来源，2026 年 8 月 1 日", "权利及许可登记 — 2026 年 8 月 2 日", "技术设计报告 — 2026 年 8 月 3 日", "财务模型 — 2026 年 8 月 4 日", "ESG 与社区计划 — 2026 年 8 月 5 日"], back: "返回发起方路径", email: "就项目准备联系 DESCO" };

export function modelFileCopy(locale: Locale): ModelFileCopy { return copy[locale]; }
