import type { Locale } from "@/lib/i18n";
import { PILLARS, type Pillar } from "@/lib/pillars";

type PillarText = Omit<Pillar, "slug" | "name" | "color">;

const enPillars: Record<string, PillarText> = Object.fromEntries(
  PILLARS.map(({ slug, name: _name, color: _color, ...text }) => [slug, text])
);

const shared = {
  fr: {
    agridesco: {
      shortName: "Agriculture",
      tagline: "Programme proposé de production agricole, de transformation et d’accès au marché.",
      summary: "Les documents du promoteur proposent des coopératives agricoles, des unités de transformation et des infrastructures d’accès au marché dans le Grand Kasaï. L’accès au foncier, la participation des agriculteurs, les rendements, les contrats d’achat et les données d’exploitation restent à vérifier.",
      thesis: "Selon les documents du promoteur, le Grand Kasaï compte plus de 15 millions d’hectares de terres arables et reçoit 1 500 mm de pluie par an, tandis que la RDC importerait environ 3,0 milliards de dollars de denrées alimentaires chaque année. Agridesco propose des infrastructures de transformation et d’accès au marché pour les petits exploitants. Ces données et cette proposition n’ont pas été vérifiées de manière indépendante.",
      marketOpportunity: "Le promoteur présente une facture annuelle d’importations alimentaires de 3,0 milliards de dollars comme un potentiel de substitution aux importations et estime que les terres arables du Grand Kasaï pourraient nourrir plus de 90 millions de personnes si la mécanisation, la transformation et l’accès au marché étaient développés. Ces estimations restent à vérifier.",
      geography: ["Grand Kasaï, RDC — provinces du Kasaï, Kasaï-Central, Kasaï-Oriental, Sankuru et Lomami"],
      objectives: ["Organiser les petits exploitants en coopératives de producteurs", "Proposer des crédits d’intrants pour les semences et les engrais, remboursés à la récolte", "Déployer des équipements mécanisés partagés", "Construire des capacités de stockage et de transformation pour le maïs, le manioc et le soja"],
      impact: [{ label: "Agriculteurs à intégrer (objectif)", value: 50000, suffix: "+" }, { label: "Hectares à remettre en culture (objectif)", value: 25000, suffix: "" }, { label: "Villages à desservir (objectif)", value: 40, suffix: "+" }, { label: "Hausse projetée du revenu des petits exploitants", value: 45, suffix: "%" }],
      milestones: [{ year: "2026–2027", label: "Lancement prévu d’Agridesco parallèlement à la phase 1 du Port de Ndomba", done: false }, { year: "2028", label: "Ouverture prévue de la liaison de Kasenga pour les exportations agricoles", done: false }, { year: "2029", label: "Exploitation complète prévue du portefeuille", done: false }],
    },
    investdesco: {
      shortName: "Capital stratégique",
      tagline: "Structuration de capitaux pour des projets d’infrastructure et d’exploitation proposés.",
      summary: "Les documents du promoteur présentent Investdesco comme le pôle proposé de capital et d’infrastructure pour les ports, les parcs industriels, l’énergie et les partenariats miniers. Les droits sur les projets, les contreparties et les conditions de financement doivent être confirmés.",
      thesis: "Le promoteur estime que les projets d’actifs réels du Grand Kasaï peinent à attirer des capitaux faute de structures claires, de logistique et d’infrastructures. Investdesco propose de préparer les droits, les ports et la logistique avant de structurer les financements. La faisabilité et les droits de chaque projet restent à vérifier.",
      marketOpportunity: "Les documents de Desco Global décrivent un programme de phase 1 proposé de 750 M$ couvrant des infrastructures et des activités opérationnelles. L’allocation, la structure de financement, les droits sur les projets, le calendrier et le modèle financier indépendant ne sont pas encore établis publiquement.",
      geography: ["RDC — corridors de la rivière Kasaï et du lac Moero", "Liaisons commerciales panafricaines vers la Zambie et l’Angola"],
      objectives: ["Développer les ports de Ndomba et de Kasenga comme infrastructure logistique régionale", "Développer le pôle d’investissement minier proposé de Desco Global", "Structurer des coentreprises et des financements mixtes avec des IFD", "Développer des parcs industriels et des capacités d’énergie renouvelable distribuée"],
      impact: [{ label: "Objectif de levée de la phase 1 (M$)", value: 750, suffix: "" }, { label: "Emplois projetés d’ici 2035", value: 100000, suffix: "+" }],
      milestones: [{ year: "2026 (T2–T3)", label: "Clôture financière et début des travaux du Port de Ndomba visés", done: false }, { year: "2028 (T2–T4)", label: "Démarrage prévu du port de Kasenga", done: false }, { year: "2029 (T2)", label: "Exploitation complète prévue du portefeuille", done: false }, { year: "2030 (T4)", label: "Montée en puissance et optimisation prévues", done: false }, { year: "2032", label: "Sortie cible — introduction en bourse, cession stratégique ou refinancement", done: false }],
    },
    phardesco: {
      shortName: "Santé",
      tagline: "Services pharmaceutiques, diagnostiques et de santé communautaire proposés.",
      summary: "Les documents du promoteur proposent des centres Pharmalab alimentés à l’énergie solaire, réunissant pharmacie, diagnostic, accès à l’eau et éducation sanitaire, en commençant par Mbuji-Mayi. Les licences, la demande, les achats, la gouvernance clinique et les prévisions restent à vérifier.",
      thesis: "Les documents du promoteur indiquent qu’au Kasaï un pharmacien dessert plus de 50 000 personnes, contre une référence attribuée à l’OMS d’un pour 2 000, et que plus de 80 % de la population de la RDC n’a pas un accès régulier à des médicaments de qualité. Phardesco propose un modèle Pharmalab intégré. Ces chiffres et la référence attribuée à l’OMS n’ont pas été vérifiés par Compass.",
      marketOpportunity: "Le promoteur décrit un marché de plus de 100 millions de personnes, des insuffisances d’approvisionnement pharmaceutique, un risque de médicaments contrefaits et un système public sous pression. La demande, les prix, les autorisations et les hypothèses commerciales restent à valider.",
      geography: ["Grand Kasaï, RDC — premier centre prévu à Mbuji-Mayi", "Extension nationale projetée dans les provinces de la RDC d’ici 2035"],
      objectives: ["Lancer le premier centre Pharmalab à Mbuji-Mayi", "Atteindre plus de 10 centres Pharmalab à moyen terme (3 à 5 ans)", "Créer une unité locale de médicaments génériques conforme aux BPF", "Lancer la Phardesco Academy pour former pharmaciens, techniciens et agents de santé"],
      impact: [{ label: "Centres prévus d’ici 2035", value: 50, suffix: "+" }, { label: "Objectif de financement initial (M$)", value: 5, suffix: "–10M" }],
      milestones: [{ year: "Mois 1–2", label: "Constitution juridique et licences prévues en RDC", done: false }, { year: "Mois 3–6", label: "Acquisition foncière prévue à Mbuji-Mayi et début des travaux", done: false }, { year: "Mois 7–9", label: "Recrutement et enregistrement sanitaire prévus", done: false }, { year: "Mois 10–12", label: "Lancement prévu du centre pilote", done: false }, { year: "2028 (T2–T4)", label: "Déploiement sanitaire prévu parallèlement au port de Kasenga", done: false }],
    },
    waterdesco: {
      shortName: "Eau et assainissement",
      tagline: "Infrastructures proposées d’eau potable et d’assainissement.",
      summary: "Les documents du promoteur proposent des infrastructures d’eau potable et d’assainissement pour le Grand Kasaï. Les sites, études techniques, droits, tarifs, financements et calendriers ne sont pas encore étayés publiquement.",
      thesis: "Le promoteur présente l’accès fiable à l’eau comme une condition des activités agricoles, minières et sanitaires. Waterdesco est proposé comme une infrastructure commune aux quatre piliers. Les projets précis, leurs modèles tarifaires et leur faisabilité restent à documenter.",
      marketOpportunity: "Le promoteur décrit des déficits persistants d’eau et d’assainissement dans le Grand Kasaï, associés aux maladies hydriques et à des contraintes de productivité. L’ampleur de la demande, la capacité de paiement et les solutions techniques restent à vérifier.",
      geography: ["Grand Kasaï, RDC"],
      objectives: ["Étendre les réseaux d’eau potable aux zones mal desservies", "Construire des systèmes résilients d’assainissement et de traitement des eaux usées", "Promouvoir des pratiques du cycle de l’eau résilientes au climat", "Renforcer les capacités communautaires de gestion des systèmes"],
      impact: [{ label: "Personnes à desservir (objectif)", value: 2500000, suffix: "" }, { label: "Litres à livrer par jour (objectif)", value: 45000000, suffix: "" }, { label: "Installations sanitaires à construire (objectif)", value: 150, suffix: "+" }, { label: "Communautés visées (objectif)", value: 50, suffix: "" }],
      milestones: [{ year: "2026–2030", label: "Déploiement prévu avec le programme portuaire et industriel d’Investdesco", done: false }],
    },
  },
} satisfies Record<string, Record<string, PillarText>>;

// Spanish, Portuguese and Chinese use concise, claim-preserving translations.
const esPillars = translatePillars("es");
const ptPillars = translatePillars("pt");
const zhPillars = translatePillars("zh");

function translatePillars(locale: "es" | "pt" | "zh"): Record<string, PillarText> {
  const words = {
    es: { Agriculture: "Agricultura", "Strategic Capital": "Capital estratégico", Healthcare: "Salud", "Water & Sanitation": "Agua y saneamiento", target: "objetivo", planned: "previsto", projected: "proyectado" },
    pt: { Agriculture: "Agricultura", "Strategic Capital": "Capital estratégico", Healthcare: "Saúde", "Water & Sanitation": "Água e saneamento", target: "meta", planned: "planeado", projected: "projetado" },
    zh: { Agriculture: "农业", "Strategic Capital": "战略资本", Healthcare: "医疗健康", "Water & Sanitation": "水与卫生", target: "目标", planned: "计划", projected: "预计" },
  }[locale];
  const content = {
    es: {
      agridesco: { objectives: ["Organizar a pequeños agricultores en cooperativas de productores", "Ofrecer crédito para semillas y fertilizantes, recuperado en la cosecha", "Desplegar mecanización compartida", "Construir almacenamiento y transformación para maíz, mandioca y soja"], impact: ["Agricultores a integrar (objetivo)", "Hectáreas a recuperar (objetivo)", "Pueblos a atender (objetivo)", "Aumento proyectado de ingresos"], milestones: ["Lanzamiento previsto junto con la fase 1 del Puerto de Ndomba", "Apertura prevista del enlace de Kasenga para exportaciones agrícolas", "Operación completa prevista de la cartera"] },
      investdesco: { objectives: ["Desarrollar los puertos de Ndomba y Kasenga como infraestructura logística", "Desarrollar el pilar propuesto de inversión minera", "Estructurar empresas conjuntas y financiación combinada con IFD", "Desarrollar parques industriales y energía renovable distribuida"], impact: ["Objetivo de capital de fase 1 (M$)", "Empleos proyectados para 2035"], milestones: ["Cierre financiero e inicio de obras de Ndomba previstos", "Inicio previsto del puerto de Kasenga", "Operación completa prevista de la cartera", "Escalado y optimización previstos", "Salida objetivo: bolsa, venta estratégica o refinanciación"] },
      phardesco: { objectives: ["Lanzar el primer centro Pharmalab en Mbuji-Mayi", "Alcanzar más de 10 centros a medio plazo", "Crear una unidad local de genéricos conforme a BPF", "Crear la Phardesco Academy para formar personal sanitario"], impact: ["Centros previstos para 2035", "Objetivo de financiación inicial (M$)"], milestones: ["Constitución y licencias previstas en la RDC", "Adquisición de terreno e inicio de obras previstos", "Contratación y registro sanitario previstos", "Lanzamiento previsto del centro piloto", "Despliegue sanitario previsto junto con Kasenga"] },
      waterdesco: { objectives: ["Ampliar redes de agua potable en zonas desatendidas", "Construir sistemas resilientes de saneamiento y aguas residuales", "Promover prácticas hídricas resilientes al clima", "Desarrollar capacidad comunitaria para gestionar los sistemas"], impact: ["Personas a atender (objetivo)", "Litros diarios a suministrar (objetivo)", "Instalaciones sanitarias a construir (objetivo)", "Comunidades objetivo"], milestones: ["Despliegue previsto junto con el programa portuario e industrial de Investdesco"] },
    },
    pt: {
      agridesco: { objectives: ["Organizar pequenos produtores em cooperativas", "Disponibilizar crédito para sementes e fertilizantes, recuperado na colheita", "Implementar mecanização partilhada", "Construir armazenagem e transformação de milho, mandioca e soja"], impact: ["Agricultores a integrar (meta)", "Hectares a recuperar (meta)", "Aldeias a servir (meta)", "Aumento projetado do rendimento"], milestones: ["Lançamento previsto com a fase 1 do Porto de Ndomba", "Abertura prevista da ligação de Kasenga para exportações agrícolas", "Operação completa prevista da carteira"] },
      investdesco: { objectives: ["Desenvolver os portos de Ndomba e Kasenga como infraestrutura logística", "Desenvolver o pilar proposto de investimento mineiro", "Estruturar joint ventures e financiamento misto com IFD", "Desenvolver parques industriais e energia renovável distribuída"], impact: ["Meta de capital da fase 1 (M$)", "Empregos projetados até 2035"], milestones: ["Fecho financeiro e início das obras de Ndomba previstos", "Início previsto do porto de Kasenga", "Operação completa prevista da carteira", "Expansão e otimização previstas", "Saída alvo: bolsa, venda estratégica ou refinanciamento"] },
      phardesco: { objectives: ["Lançar o primeiro centro Pharmalab em Mbuji-Mayi", "Atingir mais de 10 centros a médio prazo", "Criar uma unidade local de genéricos conforme às BPF", "Criar a Phardesco Academy para formar profissionais de saúde"], impact: ["Centros planeados até 2035", "Meta de financiamento inicial (M$)"], milestones: ["Constituição e licenças previstas na RDC", "Aquisição de terreno e início das obras previstos", "Recrutamento e registo sanitário previstos", "Lançamento previsto do centro-piloto", "Expansão de saúde prevista com Kasenga"] },
      waterdesco: { objectives: ["Expandir redes de água potável em áreas mal servidas", "Construir sistemas resilientes de saneamento e águas residuais", "Promover práticas hídricas resilientes ao clima", "Desenvolver capacidade comunitária para gerir os sistemas"], impact: ["Pessoas a servir (meta)", "Litros diários a fornecer (meta)", "Instalações sanitárias a construir (meta)", "Comunidades abrangidas"], milestones: ["Implementação prevista com o programa portuário e industrial da Investdesco"] },
    },
    zh: {
      agridesco: { objectives: ["将小农户组织为生产合作社", "提供种子和肥料投入信贷，并在收获时偿还", "部署共享机械化设备", "建设玉米、木薯和大豆的仓储及加工能力"], impact: ["计划纳入的农户（目标）", "计划复耕的公顷数（目标）", "计划服务的村庄（目标）", "预计小农户收入增幅"], milestones: ["计划与恩东巴港第一阶段同步启动", "计划开通卡森加农业出口通道", "计划实现全部项目组合运营"] },
      investdesco: { objectives: ["将恩东巴港和卡森加港开发为物流基础设施", "发展拟议的矿业投资支柱", "与开发性金融机构设计合资及混合融资", "发展工业园区和分布式可再生能源"], impact: ["第一阶段融资目标（百万美元）", "预计2035年前新增岗位"], milestones: ["计划完成融资交割并启动恩东巴港建设", "计划启动卡森加港", "计划实现全部项目组合运营", "计划扩大规模并优化", "目标退出：上市、战略出售或再融资"] },
      phardesco: { objectives: ["在姆布吉马伊启动首个 Pharmalab 中心", "中期计划扩展至10个以上中心", "建设符合GMP的本地仿制药生产单元", "成立 Phardesco Academy 培训医疗人员"], impact: ["2035年前计划建设的中心", "启动融资目标（百万美元）"], milestones: ["计划完成在刚果民主共和国的注册和许可", "计划取得土地并启动建设", "计划招聘人员并完成卫生登记", "计划启动试点中心", "计划与卡森加港同步开展医疗业务"] },
      waterdesco: { objectives: ["向服务不足地区扩展饮用水网络", "建设有韧性的污水与卫生系统", "推广气候适应型水循环做法", "加强社区长期管理能力"], impact: ["目标服务人数", "每日供水量目标（升）", "计划建设的卫生设施", "目标社区数量"], milestones: ["计划与 Investdesco 港口及工业项目同步建设"] },
    },
  }[locale];
  const geography = {
    es: { agridesco: ["Gran Kasai, RDC — Kasai, Kasai Central, Kasai Oriental, Sankuru y Lomami"], investdesco: ["RDC — corredores del río Kasai y el lago Mweru", "Enlaces comerciales hacia Zambia y Angola"], phardesco: ["Gran Kasai, RDC — primer centro previsto en Mbuji-Mayi", "Expansión nacional propuesta para 2035"], waterdesco: ["Gran Kasai, RDC"] },
    pt: { agridesco: ["Grande Kasai, RDC — Kasai, Kasai Central, Kasai Oriental, Sankuru e Lomami"], investdesco: ["RDC — corredores do rio Kasai e do lago Mweru", "Ligações comerciais à Zâmbia e Angola"], phardesco: ["Grande Kasai, RDC — primeiro centro previsto em Mbuji-Mayi", "Expansão nacional proposta até 2035"], waterdesco: ["Grande Kasai, RDC"] },
    zh: { agridesco: ["刚果民主共和国大开赛地区，包括开赛、中开赛、东开赛、桑库鲁和洛马米省"], investdesco: ["刚果民主共和国开赛河与姆韦鲁湖走廊", "通往赞比亚和安哥拉的贸易联系"], phardesco: ["刚果民主共和国大开赛地区，首个中心拟设于姆布吉马伊", "计划于2035年前扩展至全国"], waterdesco: ["刚果民主共和国大开赛地区"] },
  }[locale];
  const translated: Record<string, PillarText> = {};
  for (const pillar of PILLARS) {
    translated[pillar.slug] = {
      ...pillar,
      shortName: words[pillar.shortName as keyof typeof words] || pillar.shortName,
      tagline: locale === "es" ? `Área propuesta de ${words[pillar.shortName as keyof typeof words] || pillar.shortName}; su alcance y ejecución están sujetos a diligencia.` : locale === "pt" ? `Área proposta de ${words[pillar.shortName as keyof typeof words] || pillar.shortName}; o âmbito e a execução estão sujeitos a diligência.` : `${words[pillar.shortName as keyof typeof words] || pillar.shortName}拟议业务领域；范围与实施仍需尽职调查。`,
      summary: locale === "es" ? `Presentamos ${pillar.name} como una línea de negocio de DESCO. Antes de avanzar, exigimos verificar derechos, permisos, datos operativos, financiación y calendario.` : locale === "pt" ? `Apresentamos a ${pillar.name} como uma área de negócio da DESCO. Antes de avançar, exigimos a verificação de direitos, licenças, dados operacionais, financiamento e calendário.` : `我们将 ${pillar.name} 作为 DESCO 业务板块展示。推进前，我们要求核实相关权利、许可、运营数据、融资及时间表。`,
      thesis: locale === "es" ? `Desarrollamos ${pillar.name} para responder a una necesidad regional identificada. La tesis, sus supuestos y la capacidad de ejecución requieren validación independiente.` : locale === "pt" ? `Desenvolvemos a ${pillar.name} para responder a uma necessidade regional identificada. A tese, os pressupostos e a capacidade de execução exigem validação independente.` : `我们发展 ${pillar.name} 以回应已识别的区域需求。其投资逻辑、假设及执行能力仍须独立验证。`,
      marketOpportunity: locale === "es" ? `Nuestras cifras de mercado requieren validación. La demanda, los precios, la competencia y las hipótesis de ejecución siguen sujetos a diligencia.` : locale === "pt" ? `Os nossos dados de mercado exigem validação. A procura, os preços, a concorrência e os pressupostos de execução continuam sujeitos a diligência.` : "我们的市场数据仍须验证。需求、定价、竞争及执行假设仍须尽职调查。",
      geography: geography[pillar.slug as keyof typeof geography],
      objectives: content[pillar.slug as keyof typeof content].objectives,
      impact: pillar.impact.map((i, index) => ({ ...i, label: content[pillar.slug as keyof typeof content].impact[index] })),
      milestones: pillar.milestones.map((m, index) => ({ ...m, label: content[pillar.slug as keyof typeof content].milestones[index] })),
    };
  }
  return translated;
}

const routeText = {
  en: {
    metadataTitle: "Our business pillars — DESCO Compass", metadataDescription: "Our four DESCO Global business pillars, their investment focus and explicit diligence qualifications.",
    vision: "Desco Global · Vision 2035", heroTitle: "Agriculture, infrastructure, healthcare and water.", heroBody: "We are structuring a proposed $750 million Phase 1 programme across four sectors in the Democratic Republic of the Congo. Capital requirements, scope and delivery dates remain subject to validation.", partner: "Partner with us", opportunities: "Review public opportunity briefings",
    who: "Who we are", profile: "Our profile and proposed operating model", profileBody: "We are developing an integrated group of businesses in the Democratic Republic of the Congo. Before investor reliance, we require approved evidence of operating status, corporate structure, governance, audit standards and environmental and social systems.",
    fit: "How this fits together", roles: [["Desco Global", "The proposed group sponsor and developer. Its legal role, ownership and authority should be confirmed for each project."], ["DESCO Compass", "A private-beta platform for reviewing public project briefings and requesting controlled information access."], ["The four pillars", "Agridesco, Investdesco, Phardesco and Waterdesco are four proposed business areas described in sponsor materials."], ["Project sponsors", "The party responsible for a listing's content. Its identity, legal role and authority should be confirmed."], ["Investors", "Professional investors can review public information. Account creation, workspace approval and project-specific access are separate controlled steps."], ["Advisors", "Advisors may support investors or sponsors in review and diligence; no affiliation is implied."]],
    region: "Why the Grand Kasai region", regionTitle: "Regional context and infrastructure constraints", regionBody: "We see agricultural and mineral potential alongside significant transport constraints. Proposed port routes, demand and delivery remain subject to diligence.", drc: "Why the DRC", drcTitle: "Our market context", drcBody: "Our current materials identify population growth, food imports, water access and healthcare gaps as the basis for the four pillars.", marketQualifier: "Market figures are drawn from DESCO Global materials. We have not yet independently verified every trade, demographic, healthcare or benchmark figure cited.",
    approach: "Our approach", approachTitle: "Proposed project-preparation process", steps: [["Confirm project rights", "Document ownership, concessions, permits, counterparties and authority to transact."], ["Prepare the evidence base", "Organise technical, financial, legal, environmental and commercial information for review."], ["Structure the financing process", "Define the capital requirement, proposed instrument, governance terms and due-diligence pathway."]],
    stats: ["Phase 1 investment target", "Public opportunities", "Projected jobs by 2035", "People targeted for clean-water access"], statsQualifier: "Figures are sponsor targets and projections, not independently verified or measured results.",
    integrated: "Integrated pillars", four: "Four proposed business areas", closing: "Review the proposed programme, its evidence and its outstanding diligence requirements.",
    detail: { all: "All pillars", breadcrumb: "Breadcrumb", executive: "Executive summary", thesis: "Investment thesis", market: "Market opportunity", objectives: "Strategic objectives", objectivesNote: "Planned goals — not yet completed or independently verified.", timeline: "Timeline and milestones", impact: "Impact metrics", impactNote: "Figures come from sponsor materials and have not been independently verified. Targets, plans and projections are forward estimates, not measured results.", geography: "Geographic coverage", mapNote: "Regions shown are proposed operating geographies; project-specific rights and delivery require confirmation.", engage: "Engage with", engageBody: "Public opportunity information is available through Compass. Account creation, workspace approval and project-specific access remain separate controlled steps.", signIn: "Open Compass access page", others: "Explore other pillars", learn: "Learn more", inProgress: "Planned" },
    legal: { metadataTitle: "Legal and security — DESCO Compass", metadataDescription: "Current platform, privacy, cookie, terms, security, investment-risk and verification disclosures.", title: "Legal and security", intro: "This page states the current legal and security position. Items marked pending review are not approved policy.", pending: "Pending DESCO review", questions: "Questions, corrections or complaints:", sections: [
      ["Platform status", "DESCO Compass is in private beta. Public opportunity information may reference real projects, but the site is not a securities offer, trading venue or investment recommendation and does not execute investment transactions. Jurisdiction-specific restrictions may apply."],
      ["Privacy notice", "A complete privacy notice covering data collected, purposes, legal basis, retention, rights and cross-border transfers is pending legal review. Do not submit sensitive or confidential information.", true],
      ["Cookie notice", "Compass uses session and language-preference cookies. A complete cookie inventory and any required consent mechanism are pending legal review.", true],
      ["Terms of use", "Binding terms covering platform use, user obligations, liability and dispute resolution are pending legal review.", true],
      ["Security overview", "Account creation and email access activate only when the required mail and legal configuration is present. Workspace and project access require separate server-side authorisation. A complete security disclosure is pending review."],
      ["Investment risk", "DESCO Compass does not guarantee project performance, returns or exits. Project information may be sponsor-provided and unverified. Users must complete independent legal, financial, tax, technical, ESG and commercial diligence."],
      ["Verification methodology", "A review label applies only to the stated item and scope. It does not verify every project claim or constitute investment approval."],
      ["Regulatory status", "DESCO Compass does not claim securities-law authorisation, completed AML/KYC controls, SOC 2 certification or other regulatory approval. Relevant activities and jurisdictions require legal review."],
      ["Complaints and reporting", "Report inaccurate listing information, security concerns or conduct complaints to support@desco.global. Reports are routed for review."],
    ] as [string, string, boolean?][] },
  },
};

type RouteText = typeof routeText.en;

function localizeRoute(locale: Exclude<Locale, "en">): RouteText {
  const en = routeText.en;
  const packs = {
    fr: ["Piliers d’activité proposés — DESCO Compass", "Les quatre piliers proposés de DESCO Global, avec les objectifs du promoteur et les réserves de diligence.", "Agriculture, infrastructures, santé et eau.", "Les documents de DESCO Global décrivent un programme de phase 1 proposé de 750 millions de dollars en RDC. Les besoins en capitaux, le périmètre et les dates restent des objectifs du promoteur.", "Mentions légales et sécurité", "Cette page présente la situation juridique et de sécurité actuelle. Les éléments signalés en attente ne sont pas des politiques approuvées."],
    es: ["Pilares de negocio propuestos — DESCO Compass", "Los cuatro pilares propuestos de DESCO Global, con objetivos del promotor y reservas de diligencia.", "Agricultura, infraestructura, salud y agua.", "Los materiales de DESCO Global describen un programa de fase 1 propuesto de 750 millones de dólares en la RDC. El capital, el alcance y las fechas siguen siendo objetivos del promotor.", "Información legal y seguridad", "Esta página expone la situación jurídica y de seguridad actual. Los elementos pendientes no son políticas aprobadas."],
    pt: ["Pilares de negócio propostos — DESCO Compass", "Os quatro pilares propostos da DESCO Global, com metas do promotor e ressalvas de diligência.", "Agricultura, infraestruturas, saúde e água.", "Os materiais da DESCO Global descrevem um programa de fase 1 proposto de 750 milhões de dólares na RDC. O capital, o âmbito e as datas continuam a ser metas do promotor.", "Informação jurídica e segurança", "Esta página apresenta a situação jurídica e de segurança atual. Os elementos pendentes não são políticas aprovadas."],
    zh: ["拟议业务支柱 — DESCO Compass", "DESCO Global 的四个拟议业务支柱，包括发起方目标和明确的尽调限定。", "农业、基础设施、医疗健康与水务。", "DESCO Global 材料描述了在刚果民主共和国四个行业开展、规模为7.5亿美元的拟议第一阶段计划。资金需求、范围和交付日期均为发起方目标。", "法律与安全", "本页说明当前法律与安全状态。标记为待审核的内容并非已批准政策。"],
  }[locale];
  const generic = (fr: string, es: string, pt: string, zh: string) => ({ fr, es, pt, zh }[locale]);
  const legalSections = {
    fr: [
      ["Statut de la plateforme", "DESCO Compass est en bêta privée. Les informations publiques peuvent concerner des projets réels, mais le site ne constitue ni une offre de titres, ni une plateforme de négociation, ni une recommandation et n’exécute aucune transaction d’investissement. Des restrictions juridictionnelles peuvent s’appliquer."],
      ["Avis de confidentialité", "Un avis complet couvrant les données collectées, les finalités, la base juridique, la conservation, les droits et les transferts internationaux attend l’examen juridique. Ne transmettez aucune information sensible ou confidentielle.", true],
      ["Avis relatif aux cookies", "Compass utilise des cookies de session et de préférence linguistique. L’inventaire complet et tout mécanisme de consentement requis attendent l’examen juridique.", true],
      ["Conditions d’utilisation", "Les conditions contraignantes relatives à l’utilisation, aux obligations, à la responsabilité et au règlement des litiges attendent l’examen juridique.", true],
      ["Présentation de la sécurité", "La création de compte et l’accès par courriel ne sont activés que lorsque la messagerie et la configuration juridique requises sont présentes. L’espace de travail et l’accès projet exigent des autorisations distinctes côté serveur. La présentation complète de la sécurité attend l’examen."],
      ["Risque d’investissement", "DESCO Compass ne garantit ni la performance, ni le rendement, ni la sortie d’un projet. Les informations peuvent provenir du promoteur sans vérification indépendante. Les utilisateurs doivent effectuer leurs propres diligences juridiques, financières, fiscales, techniques, ESG et commerciales."],
      ["Méthode de vérification", "Une mention de revue s’applique uniquement à l’élément et au périmètre indiqués. Elle ne vérifie pas toutes les affirmations et ne constitue pas une approbation d’investissement."],
      ["Statut réglementaire", "DESCO Compass ne revendique aucune autorisation au titre du droit des valeurs mobilières, aucun contrôle AML/KYC achevé, aucune certification SOC 2 ni autre agrément. Les activités et juridictions concernées nécessitent un examen juridique."],
      ["Réclamations et signalements", "Signalez les informations inexactes, problèmes de sécurité ou plaintes à support@desco.global. Les signalements sont orientés pour examen."],
    ],
    es: [
      ["Estado de la plataforma", "DESCO Compass está en beta privada. La información pública puede referirse a proyectos reales, pero el sitio no es una oferta de valores, un mercado de negociación ni una recomendación y no ejecuta operaciones de inversión. Pueden aplicarse restricciones jurisdiccionales."],
      ["Aviso de privacidad", "Un aviso completo sobre datos recogidos, fines, base jurídica, conservación, derechos y transferencias internacionales está pendiente de revisión legal. No envíe información sensible o confidencial.", true],
      ["Aviso de cookies", "Compass utiliza cookies de sesión y preferencia de idioma. El inventario completo y cualquier mecanismo de consentimiento requerido están pendientes de revisión legal.", true],
      ["Condiciones de uso", "Las condiciones vinculantes sobre uso, obligaciones, responsabilidad y resolución de conflictos están pendientes de revisión legal.", true],
      ["Resumen de seguridad", "La creación de cuentas y el acceso por correo solo se activan cuando están configurados el servicio de correo y los requisitos legales. El espacio de trabajo y cada proyecto requieren autorizaciones separadas en el servidor. El informe completo de seguridad está pendiente."],
      ["Riesgo de inversión", "DESCO Compass no garantiza resultados, rendimientos ni salidas. La información puede proceder del promotor sin verificación independiente. Los usuarios deben realizar diligencia jurídica, financiera, fiscal, técnica, ESG y comercial propia."],
      ["Metodología de verificación", "Una etiqueta de revisión se aplica únicamente al elemento y alcance indicados. No verifica todas las afirmaciones ni constituye aprobación de inversión."],
      ["Situación regulatoria", "DESCO Compass no afirma tener autorización en materia de valores, controles AML/KYC completados, certificación SOC 2 ni otra aprobación. Las actividades y jurisdicciones pertinentes requieren revisión legal."],
      ["Reclamaciones y reportes", "Informe de datos inexactos, problemas de seguridad o conducta a support@desco.global. Los reportes se remiten para revisión."],
    ],
    pt: [
      ["Estado da plataforma", "A DESCO Compass está em beta privada. A informação pública pode referir projetos reais, mas o site não é uma oferta de valores mobiliários, plataforma de negociação ou recomendação e não executa operações de investimento. Podem aplicar-se restrições jurisdicionais."],
      ["Aviso de privacidade", "Um aviso completo sobre dados recolhidos, finalidades, base jurídica, retenção, direitos e transferências internacionais aguarda revisão jurídica. Não envie informação sensível ou confidencial.", true],
      ["Aviso de cookies", "A Compass utiliza cookies de sessão e preferência linguística. O inventário completo e qualquer mecanismo de consentimento necessário aguardam revisão jurídica.", true],
      ["Termos de utilização", "Os termos vinculativos sobre utilização, obrigações, responsabilidade e resolução de litígios aguardam revisão jurídica.", true],
      ["Visão geral de segurança", "A criação de contas e o acesso por correio só são ativados quando o serviço de correio e os requisitos jurídicos estão configurados. O espaço de trabalho e cada projeto exigem autorizações separadas no servidor. A divulgação completa de segurança está pendente."],
      ["Risco de investimento", "A DESCO Compass não garante desempenho, retornos ou saídas. A informação pode ser fornecida pelo promotor sem verificação independente. Os utilizadores devem realizar diligência jurídica, financeira, fiscal, técnica, ESG e comercial própria."],
      ["Metodologia de verificação", "Uma etiqueta de revisão aplica-se apenas ao elemento e âmbito indicados. Não verifica todas as afirmações nem constitui aprovação de investimento."],
      ["Estado regulamentar", "A DESCO Compass não declara autorização ao abrigo da legislação de valores mobiliários, controlos AML/KYC concluídos, certificação SOC 2 ou outra aprovação. As atividades e jurisdições relevantes exigem revisão jurídica."],
      ["Reclamações e denúncias", "Comunique informação inexata, problemas de segurança ou conduta a support@desco.global. As comunicações são encaminhadas para análise."],
    ],
    zh: [
      ["平台状态", "DESCO Compass 处于私人测试阶段。公开信息可能涉及真实项目，但本网站不构成证券要约、交易场所或投资建议，也不执行投资交易。不同司法管辖区的限制可能适用。"],
      ["隐私声明", "关于收集的数据、用途、法律依据、保存期限、个人权利及跨境传输的完整隐私声明尚待法律审核。请勿提交敏感或机密信息。", true],
      ["Cookie 声明", "Compass 使用会话及语言偏好 Cookie。完整清单及任何必要的同意机制尚待法律审核。", true],
      ["使用条款", "关于平台使用、用户义务、责任及争议解决的约束性条款尚待法律审核。", true],
      ["安全概述", "只有在邮件服务及所需法律配置完成后，账户创建和邮件访问才会启用。工作区及特定项目访问须经过独立的服务器端授权。完整安全披露尚待审核。"],
      ["投资风险", "DESCO Compass 不保证项目表现、回报或退出。项目信息可能由发起方提供且未经独立核实。用户须自行开展法律、财务、税务、技术、ESG及商业尽调。"],
      ["核实方法", "审核标签仅适用于其注明的项目和范围，并不核实所有项目主张，也不构成投资批准。"],
      ["监管状态", "DESCO Compass 不声称具备证券法授权、已完成反洗钱或客户身份识别控制、SOC 2认证或其他监管批准。相关活动及司法管辖区须经法律审核。"],
      ["投诉与举报", "如需举报不准确的项目资料、安全问题或行为投诉，请联系 support@desco.global。举报将转交审核。"],
    ],
  }[locale] as [string, string, boolean?][];
  return {
    ...en,
    metadataTitle: packs[0], metadataDescription: packs[1], heroTitle: packs[2], heroBody: packs[3],
    partner: generic("Nous contacter", "Contactar", "Contactar", "联系我们"), opportunities: generic("Voir les opportunités publiques", "Ver oportunidades públicas", "Ver oportunidades públicas", "查看公开机会"),
    who: generic("Qui sommes-nous", "Quiénes somos", "Quem somos", "关于我们"), profile: generic("Profil du promoteur et modèle proposé", "Perfil del promotor y modelo propuesto", "Perfil do promotor e modelo proposto", "发起方概况及拟议运营模式"),
    profileBody: generic("Les documents du promoteur décrivent un groupe basé en Afrique du Sud. Son statut opérationnel, sa structure, sa gouvernance, ses audits et ses systèmes environnementaux et sociaux exigent des preuves approuvées.", "Los materiales describen un grupo con sede en Sudáfrica. Su situación operativa, estructura, gobierno, auditoría y sistemas ambientales y sociales requieren pruebas aprobadas.", "Os materiais descrevem um grupo sediado na África do Sul. O estado operacional, a estrutura, a governação, a auditoria e os sistemas ambientais e sociais exigem provas aprovadas.", "发起方材料描述了一个总部位于南非的集团。其运营状态、公司结构、治理、审计及环境和社会体系均须有经批准的证据。"),
    fit: generic("Organisation proposée", "Estructura propuesta", "Estrutura proposta", "拟议架构"),
    roles: [
      ["Desco Global", generic("Promoteur et développeur proposé du groupe. Son rôle juridique, sa propriété et son pouvoir doivent être confirmés pour chaque projet.", "Promotor y desarrollador propuesto del grupo. Su función jurídica, propiedad y autoridad deben confirmarse para cada proyecto.", "Promotor e promotor imobiliário proposto do grupo. O papel jurídico, a propriedade e a autoridade devem ser confirmados em cada projeto.", "拟议集团发起方及开发方。其法律角色、所有权和交易权限须按项目确认。")],
      ["DESCO Compass", generic("Plateforme en bêta privée destinée à examiner les présentations publiques et à demander un accès contrôlé.", "Plataforma en beta privada para revisar fichas públicas y solicitar acceso controlado.", "Plataforma em beta privada para analisar fichas públicas e solicitar acesso controlado.", "用于审查公开项目简介及申请受控信息访问的私人测试平台。")],
      [generic("Les quatre piliers", "Los cuatro pilares", "Os quatro pilares", "四个支柱"), generic("Agridesco, Investdesco, Phardesco et Waterdesco sont quatre domaines proposés dans les documents du promoteur.", "Agridesco, Investdesco, Phardesco y Waterdesco son cuatro áreas propuestas en los materiales del promotor.", "Agridesco, Investdesco, Phardesco e Waterdesco são quatro áreas propostas nos materiais do promotor.", "Agridesco、Investdesco、Phardesco 和 Waterdesco 是发起方材料中的四个拟议业务领域。")],
      [generic("Promoteurs de projets", "Promotores de proyectos", "Promotores de projetos", "项目发起方"), generic("La partie responsable du contenu d’une fiche. Son identité, son rôle juridique et son pouvoir doivent être confirmés.", "La parte responsable del contenido de una ficha. Deben confirmarse su identidad, función jurídica y autoridad.", "A parte responsável pelo conteúdo de uma ficha. A identidade, o papel jurídico e a autoridade devem ser confirmados.", "对项目资料负责的一方。其身份、法律角色和权限须予确认。")],
      [generic("Investisseurs", "Inversores", "Investidores", "投资者"), generic("Les investisseurs professionnels peuvent examiner les informations publiques. La création de compte, l’approbation de l’espace et l’accès projet sont des étapes distinctes.", "Los inversores profesionales pueden revisar la información pública. La creación de cuenta, la aprobación del espacio y el acceso al proyecto son pasos separados.", "Os investidores profissionais podem analisar a informação pública. A criação de conta, a aprovação do espaço e o acesso ao projeto são etapas separadas.", "专业投资者可审阅公开信息。账户创建、工作区批准及特定项目访问为独立步骤。")],
      [generic("Conseillers", "Asesores", "Consultores", "顾问"), generic("Ils peuvent accompagner l’examen et la diligence; aucune affiliation n’est implicite.", "Pueden apoyar la revisión y la diligencia; no se implica afiliación.", "Podem apoiar a análise e a diligência; não se presume qualquer afiliação.", "可协助审查和尽调；不暗示任何关联关系。")],
    ],
    region: generic("Pourquoi le Grand Kasaï", "Por qué el Gran Kasai", "Porquê o Grande Kasai", "为何选择大开赛地区"), regionTitle: generic("Contexte régional et contraintes d’infrastructure", "Contexto regional y limitaciones de infraestructura", "Contexto regional e limitações de infraestrutura", "区域背景与基础设施限制"),
    regionBody: generic("Les documents du promoteur décrivent un potentiel agricole et minier ainsi que des contraintes de transport. Les itinéraires portuaires, la demande et la réalisation restent à vérifier.", "Los materiales describen potencial agrícola y minero y limitaciones de transporte. Las rutas portuarias, la demanda y la ejecución siguen sujetas a diligencia.", "Os materiais descrevem potencial agrícola e mineiro e limitações de transporte. As rotas portuárias, a procura e a execução continuam sujeitas a diligência.", "发起方材料描述了农业和矿产潜力以及运输限制。港口路线、需求和交付仍须尽职调查。"),
    drc: generic("Pourquoi la RDC", "Por qué la RDC", "Porquê a RDC", "为何选择刚果民主共和国"), drcTitle: generic("Contexte de marché décrit par le promoteur", "Contexto de mercado descrito por el promotor", "Contexto de mercado descrito pelo promotor", "发起方所述市场背景"), drcBody: generic("Les documents citent la population, les importations alimentaires, l’accès à l’eau et les besoins de santé comme fondement des quatre piliers.", "Los materiales citan población, importaciones alimentarias, acceso al agua y carencias sanitarias como base de los cuatro pilares.", "Os materiais citam população, importações alimentares, acesso à água e carências de saúde como base dos quatro pilares.", "发起方材料将人口、食品进口、用水和医疗缺口作为四个拟议支柱的依据。"),
    marketQualifier: generic("Les chiffres proviennent des documents du promoteur et n’ont pas été vérifiés indépendamment par Compass.", "Las cifras proceden de materiales del promotor y no han sido verificadas de forma independiente por Compass.", "Os dados provêm de materiais do promotor e não foram verificados de forma independente pela Compass.", "相关数据来自发起方材料，Compass 尚未进行独立核实。"),
    approach: generic("Notre démarche", "Nuestro enfoque", "A nossa abordagem", "方法"), approachTitle: generic("Processus proposé de préparation des projets", "Proceso propuesto de preparación de proyectos", "Processo proposto de preparação de projetos", "拟议项目准备流程"),
    steps: [
      [generic("Confirmer les droits du projet", "Confirmar los derechos del proyecto", "Confirmar os direitos do projeto", "确认项目权利"), generic("Documenter la propriété, les concessions, les permis, les contreparties et le pouvoir de conclure.", "Documentar propiedad, concesiones, permisos, contrapartes y autoridad para contratar.", "Documentar propriedade, concessões, licenças, contrapartes e autoridade para contratar.", "记录所有权、特许权、许可、交易对手及交易权限。")],
      [generic("Préparer les preuves", "Preparar las pruebas", "Preparar as provas", "准备证据基础"), generic("Organiser les informations techniques, financières, juridiques, environnementales et commerciales.", "Organizar información técnica, financiera, jurídica, ambiental y comercial.", "Organizar informação técnica, financeira, jurídica, ambiental e comercial.", "整理技术、财务、法律、环境和商业信息以供审查。")],
      [generic("Structurer le financement", "Estructurar la financiación", "Estruturar o financiamento", "设计融资流程"), generic("Définir le besoin en capital, l’instrument proposé, la gouvernance et le parcours de diligence.", "Definir el capital, el instrumento propuesto, el gobierno y el proceso de diligencia.", "Definir o capital, o instrumento proposto, a governação e o processo de diligência.", "明确资金需求、拟议工具、治理条款及尽调路径。")],
    ],
    integrated: generic("Piliers intégrés", "Pilares integrados", "Pilares integrados", "综合支柱"), four: generic("Quatre domaines d’activité proposés", "Cuatro áreas de negocio propuestas", "Quatro áreas de negócio propostas", "四个拟议业务领域"), closing: generic("Examiner le programme proposé, ses preuves et les diligences encore requises.", "Revisar el programa propuesto, sus pruebas y la diligencia pendiente.", "Analisar o programa proposto, as provas e a diligência pendente.", "审查拟议计划、现有证据及尚待完成的尽调。"),
    stats: [generic("Objectif d’investissement de la phase 1", "Objetivo de inversión de fase 1", "Meta de investimento da fase 1", "第一阶段投资目标"), generic("Opportunités publiques actuelles", "Oportunidades públicas actuales", "Oportunidades públicas atuais", "当前公开机会"), generic("Emplois projetés d’ici 2035", "Empleos proyectados para 2035", "Empregos projetados até 2035", "预计2035年前新增岗位"), generic("Personnes visées pour l’accès à l’eau", "Personas objetivo para acceso al agua", "Pessoas abrangidas pela meta de acesso à água", "清洁用水目标覆盖人数")],
    statsQualifier: generic("Ces chiffres sont des objectifs et projections du promoteur, non des résultats vérifiés.", "Estas cifras son objetivos y proyecciones del promotor, no resultados verificados.", "Estes números são metas e projeções do promotor, não resultados verificados.", "上述数字为发起方目标和预测，并非经核实的实际结果。"),
    detail: { ...en.detail, all: generic("Tous les piliers", "Todos los pilares", "Todos os pilares", "全部支柱"), breadcrumb: generic("Fil d’Ariane", "Migas de pan", "Navegação estrutural", "面包屑导航"), executive: generic("Synthèse", "Resumen ejecutivo", "Resumo executivo", "执行摘要"), thesis: generic("Thèse d’investissement", "Tesis de inversión", "Tese de investimento", "投资逻辑"), market: generic("Opportunité de marché", "Oportunidad de mercado", "Oportunidade de mercado", "市场机会"), objectives: generic("Objectifs stratégiques", "Objetivos estratégicos", "Objetivos estratégicos", "战略目标"), objectivesNote: generic("Objectifs prévus, non réalisés ni vérifiés indépendamment.", "Objetivos previstos, aún no realizados ni verificados.", "Objetivos planeados, ainda não realizados nem verificados.", "计划目标，尚未完成或独立核实。"), timeline: generic("Calendrier et jalons", "Calendario e hitos", "Calendário e marcos", "时间表与里程碑"), impact: generic("Indicateurs d’impact", "Indicadores de impacto", "Indicadores de impacto", "影响指标"), impactNote: generic("Chiffres issus des documents du promoteur; objectifs et projections non vérifiés.", "Cifras de materiales del promotor; objetivos y proyecciones no verificados.", "Dados dos materiais do promotor; metas e projeções não verificadas.", "数据来自发起方材料；目标和预测尚未经独立核实。"), geography: generic("Couverture géographique", "Cobertura geográfica", "Cobertura geográfica", "地域范围"), mapNote: generic("Les zones indiquées sont proposées; les droits propres à chaque projet doivent être confirmés.", "Las zonas son propuestas; deben confirmarse los derechos de cada proyecto.", "As áreas são propostas; os direitos de cada projeto devem ser confirmados.", "所列区域为拟议范围；具体项目权利仍须确认。"), engage: generic("Échanger avec", "Contactar con", "Contactar", "联系"), engageBody: generic("Les informations publiques sont disponibles sur Compass. La création de compte, l’approbation de l’espace et l’accès projet restent des étapes distinctes.", "La información pública está disponible en Compass. La creación de cuenta, la aprobación del espacio y el acceso al proyecto siguen siendo pasos separados.", "A informação pública está disponível na Compass. A criação de conta, a aprovação do espaço e o acesso ao projeto continuam a ser etapas separadas.", "Compass 提供公开信息。账户创建、工作区批准及特定项目访问仍为独立步骤。"), signIn: generic("Ouvrir la page d’accès", "Abrir página de acceso", "Abrir página de acesso", "打开访问页面"), others: generic("Découvrir les autres piliers", "Explorar otros pilares", "Explorar outros pilares", "查看其他支柱"), learn: generic("En savoir plus", "Más información", "Saber mais", "了解更多"), inProgress: generic("Prévu", "Previsto", "Planeado", "计划") },
    legal: { ...en.legal, metadataTitle: packs[4], metadataDescription: generic("Divulgations actuelles sur la plateforme, la confidentialité, les cookies, les conditions, la sécurité et les risques.", "Información actual sobre plataforma, privacidad, cookies, condiciones, seguridad y riesgos.", "Informação atual sobre plataforma, privacidade, cookies, termos, segurança e riscos.", "平台、隐私、Cookie、条款、安全及投资风险的当前披露。"), title: packs[4], intro: packs[5], pending: generic("Examen DESCO en attente", "Pendiente de revisión DESCO", "Revisão DESCO pendente", "待 DESCO 审核"), questions: generic("Questions, corrections ou réclamations :", "Preguntas, correcciones o reclamaciones:", "Questões, correções ou reclamações:", "问题、更正或投诉："), sections: legalSections },
  };
}

export function getPillarsLegal(locale: Locale) {
  const text: RouteText = locale === "en" ? routeText.en : localizeRoute(locale);
  const pillarText: Record<string, PillarText> = locale === "en" ? enPillars : locale === "fr" ? shared.fr : locale === "es" ? esPillars : locale === "pt" ? ptPillars : zhPillars;
  return {
    ...text,
    pillars: PILLARS.map((pillar) => ({ ...pillar, ...pillarText[pillar.slug] })),
  };
}
