import type { Locale } from "@/lib/i18n";
import { PILLARS, type Pillar } from "@/lib/pillars";

type PillarText = Omit<Pillar, "slug" | "name" | "color">;

const enPillars: Record<string, PillarText> = Object.fromEntries(
  PILLARS.map(({ slug, name: _name, color: _color, ...text }) => [slug, text])
);

const shared = {
  fr: {
    agridesco: {
      shortName: "Agriculture",
      tagline: "Programme proposé de production agricole, de transformation et d’accès au marché.",
      summary: "Les documents du promoteur proposent des coopératives agricoles, des unités de transformation et des infrastructures d’accès au marché dans le Grand Kasaï. L’accès au foncier, la participation des agriculteurs, les rendements, les contrats d’achat et les données d’exploitation restent à vérifier.",
      thesis: "Les documents du promoteur proposent un réseau de coopératives de petits exploitants, de mécanisation partagée, de stockage et de transformation dans le Grand Kasaï. Le dossier public dépend de preuves vérifiées sur le foncier, la participation, les rendements, les performances et les achats.",
      marketOpportunity: "Le promoteur présente les importations alimentaires et les capacités limitées de transformation comme contexte commercial. Des données de marché actuelles et attribuables ainsi qu’une étude indépendante de la demande sont nécessaires avant toute décision d’investissement.",
      geography: ["Grand Kasaï, RDC — provinces du Kasaï, Kasaï-Central, Kasaï-Oriental, Sankuru et Lomami"],
      objectives: ["Organiser les petits exploitants en coopératives de producteurs", "Proposer des crédits d’intrants pour les semences et les engrais, remboursés à la récolte", "Déployer des équipements mécanisés partagés", "Construire des capacités de stockage et de transformation pour le maïs, le manioc et le soja"],
      impact: [],
      milestones: [{ year: "Étape 1", label: "Confirmer l’entité, le foncier, les agriculteurs participants et les données de référence", done: false }, { year: "Étape 2", label: "Valider le pilote, la demande, les achats, l’économie unitaire et les sauvegardes", done: false }, { year: "Étape 3", label: "Définir le déploiement finançable après examen des preuves du pilote", done: false }],
    },
    investdesco: {
      shortName: "Capital stratégique",
      tagline: "Structuration de capitaux pour des projets d’infrastructure et d’exploitation proposés.",
      summary: "Les documents du promoteur présentent Investdesco comme le pôle proposé de capital et d’infrastructure pour les ports, les parcs industriels, l’énergie et les partenariats miniers. Les droits sur les projets, les contreparties et les conditions de financement doivent être confirmés.",
      thesis: "Le promoteur estime que les projets d’actifs réels du Grand Kasaï peinent à attirer des capitaux faute de structures claires, de logistique et d’infrastructures. Investdesco propose de préparer les droits, les ports et la logistique avant de structurer les financements. La faisabilité et les droits de chaque projet restent à vérifier.",
      marketOpportunity: "Nous définissons les besoins en capitaux projet par projet. Aucun objectif agrégé de levée n’est publié tant que les droits, coûts, séquences et structures de financement restent en préparation.",
      geography: ["RDC — corridors de la rivière Kasaï et du lac Moero", "Liaisons commerciales panafricaines vers la Zambie et l’Angola"],
      objectives: ["Développer les ports de Ndomba et de Kasenga comme infrastructure logistique régionale", "Développer le pôle d’investissement minier proposé de Desco Global", "Structurer des coentreprises et des financements mixtes avec des IFD", "Développer des parcs industriels et des capacités d’énergie renouvelable distribuée"],
      impact: [],
      milestones: [{ year: "Étape 1", label: "Confirmer les droits, les promoteurs, les contreparties et les pouvoirs", done: false }, { year: "Étape 2", label: "Valider la faisabilité, la demande, les sauvegardes, les coûts et la séquence", done: false }, { year: "Étape 3", label: "Définir les structures de capital et les conditions d’engagement approuvées", done: false }],
    },
    phardesco: {
      shortName: "Santé",
      tagline: "Services pharmaceutiques, diagnostiques et de santé communautaire proposés.",
      summary: "Les documents du promoteur proposent des centres Pharmalab alimentés à l’énergie solaire, réunissant pharmacie, diagnostic, accès à l’eau et éducation sanitaire, en commençant par Mbuji-Mayi. Les licences, la demande, les achats, la gouvernance clinique et les prévisions restent à vérifier.",
      thesis: "Les documents du promoteur proposent des centres solaires réunissant pharmacie, diagnostic, accès à l’eau et éducation sanitaire. Les licences, la demande, la gouvernance clinique, les achats, la chaîne du froid et les prévisions exigent un examen indépendant.",
      marketOpportunity: "Les documents du promoteur citent un accès limité aux pharmaciens et aux médicaments de qualité. Les ratios, la population et la demande adressable doivent être étayés par des sources actuelles et attribuables.",
      geography: ["Grand Kasaï, RDC — premier centre prévu à Mbuji-Mayi", "Extension nationale projetée dans les provinces de la RDC d’ici 2035"],
      objectives: ["Lancer le premier centre Pharmalab à Mbuji-Mayi", "Atteindre plus de 10 centres Pharmalab à moyen terme (3 à 5 ans)", "Créer une unité locale de médicaments génériques conforme aux BPF", "Lancer la Phardesco Academy pour former pharmaciens, techniciens et agents de santé"],
      impact: [],
      milestones: [{ year: "Étape 1", label: "Confirmer l’entité, les licences, la gouvernance clinique et les droits sur le site", done: false }, { year: "Étape 2", label: "Valider la demande, les services, les achats, la chaîne du froid et le budget pilote", done: false }, { year: "Étape 3", label: "Fixer le calendrier après confirmation des autorisations et du financement", done: false }],
    },
    waterdesco: {
      shortName: "Eau et assainissement",
      tagline: "Infrastructures proposées d’eau potable et d’assainissement.",
      summary: "Les documents du promoteur proposent des infrastructures d’eau potable et d’assainissement pour le Grand Kasaï. Les sites, études techniques, droits, tarifs, financements et calendriers ne sont pas encore étayés publiquement.",
      thesis: "Le promoteur présente l’accès fiable à l’eau comme une condition des activités agricoles, minières et sanitaires. Waterdesco est proposé comme une infrastructure commune aux quatre piliers. Les projets précis, leurs modèles tarifaires et leur faisabilité restent à documenter.",
      marketOpportunity: "Le promoteur décrit des déficits persistants d’eau et d’assainissement dans le Grand Kasaï, associés aux maladies hydriques et à des contraintes de productivité. L’ampleur de la demande, la capacité de paiement et les solutions techniques restent à vérifier.",
      geography: ["Grand Kasaï, RDC"],
      objectives: ["Étendre les réseaux d’eau potable aux zones mal desservies", "Construire des systèmes résilients d’assainissement et de traitement des eaux usées", "Promouvoir des pratiques du cycle de l’eau résilientes au climat", "Renforcer les capacités communautaires de gestion des systèmes"],
      impact: [{ label: "Volume journalier prévu (litres)", value: 45000000, suffix: "" }, { label: "Équivalent à 50 litres par personne et par jour", value: 900000, suffix: "" }],
      milestones: [{ year: "Étape 1", label: "Rapprocher les configurations du réseau et les hypothèses de bénéficiaires", done: false }, { year: "Étape 2", label: "Achever les études sur l’eau, les sites, la demande, les tarifs et les permis", done: false }, { year: "Étape 3", label: "Définir les achats, le financement, l’exploitation et la maintenance", done: false }],
    },
  },
} satisfies Record<string, Record<string, PillarText>>;

// Spanish, Portuguese and Chinese use concise, claim-preserving translations.
const esPillars = translatePillars("es");
const ptPillars = translatePillars("pt");
const zhPillars = translatePillars("zh");

function translatePillars(locale: "es" | "pt" | "zh"): Record<string, PillarText> {
  const words = {
    es: { Agriculture: "Agricultura", "Strategic Capital": "Capital estratégico", Healthcare: "Salud", "Water & Sanitation": "Agua y saneamiento", target: "objetivo", planned: "previsto", projected: "proyectado" },
    pt: { Agriculture: "Agricultura", "Strategic Capital": "Capital estratégico", Healthcare: "Saúde", "Water & Sanitation": "Água e saneamento", target: "meta", planned: "planeado", projected: "projetado" },
    zh: { Agriculture: "农业", "Strategic Capital": "战略资本", Healthcare: "医疗健康", "Water & Sanitation": "水与卫生", target: "目标", planned: "计划", projected: "预计" },
  }[locale];
  const content = {
    es: {
      agridesco: { objectives: ["Organizar a pequeños agricultores en cooperativas de productores", "Ofrecer crédito para semillas y fertilizantes, recuperado en la cosecha", "Desplegar mecanización compartida", "Construir almacenamiento y transformación para maíz, mandioca y soja"], impact: ["Agricultores a integrar (objetivo)", "Hectáreas a recuperar (objetivo)", "Pueblos a atender (objetivo)", "Aumento proyectado de ingresos"], milestones: ["Confirmar entidad, tierras, agricultores y datos de referencia", "Validar piloto, demanda, compra, economía y salvaguardas", "Definir el despliegue financiable tras revisar el piloto"] },
      investdesco: { objectives: ["Desarrollar los puertos de Ndomba y Kasenga como infraestructura logística", "Desarrollar el pilar propuesto de inversión minera", "Estructurar empresas conjuntas y financiación combinada con IFD", "Desarrollar parques industriales y energía renovable distribuida"], impact: ["Objetivo de capital de fase 1 (M$)", "Empleos proyectados para 2035"], milestones: ["Confirmar derechos, promotores, contrapartes y autoridad", "Validar viabilidad, demanda, salvaguardas, costes y secuencia", "Definir estructuras de capital y condiciones aprobadas"] },
      phardesco: { objectives: ["Lanzar el primer centro Pharmalab en Mbuji-Mayi", "Alcanzar más de 10 centros a medio plazo", "Crear una unidad local de genéricos conforme a BPF", "Crear la Phardesco Academy para formar personal sanitario"], impact: ["Centros previstos para 2035", "Objetivo de financiación inicial (M$)"], milestones: ["Confirmar entidad, licencias, gobierno clínico y derechos del sitio", "Validar demanda, servicios, compras, cadena de frío y presupuesto", "Fijar el calendario tras confirmar permisos y financiación"] },
      waterdesco: { objectives: ["Ampliar redes de agua potable en zonas desatendidas", "Construir sistemas resilientes de saneamiento y aguas residuales", "Promover prácticas hídricas resilientes al clima", "Desarrollar capacidad comunitaria para gestionar los sistemas"], impact: ["Volumen diario de diseño (litros)", "Equivalente a 50 litros por persona y día"], milestones: ["Conciliar configuraciones y beneficiarios", "Completar estudios de agua, sitio, demanda, tarifas y permisos", "Definir compras, financiación, operación y mantenimiento"] },
    },
    pt: {
      agridesco: { objectives: ["Organizar pequenos produtores em cooperativas", "Disponibilizar crédito para sementes e fertilizantes, recuperado na colheita", "Implementar mecanização partilhada", "Construir armazenagem e transformação de milho, mandioca e soja"], impact: ["Agricultores a integrar (meta)", "Hectares a recuperar (meta)", "Aldeias a servir (meta)", "Aumento projetado do rendimento"], milestones: ["Confirmar entidade, terras, agricultores e dados de referência", "Validar piloto, procura, compra, economia e salvaguardas", "Definir a implementação financiável após analisar o piloto"] },
      investdesco: { objectives: ["Desenvolver os portos de Ndomba e Kasenga como infraestrutura logística", "Desenvolver o pilar proposto de investimento mineiro", "Estruturar joint ventures e financiamento misto com IFD", "Desenvolver parques industriais e energia renovável distribuída"], impact: ["Meta de capital da fase 1 (M$)", "Empregos projetados até 2035"], milestones: ["Confirmar direitos, promotores, contrapartes e autoridade", "Validar viabilidade, procura, salvaguardas, custos e sequência", "Definir estruturas de capital e condições aprovadas"] },
      phardesco: { objectives: ["Lançar o primeiro centro Pharmalab em Mbuji-Mayi", "Atingir mais de 10 centros a médio prazo", "Criar uma unidade local de genéricos conforme às BPF", "Criar a Phardesco Academy para formar profissionais de saúde"], impact: ["Centros planeados até 2035", "Meta de financiamento inicial (M$)"], milestones: ["Confirmar entidade, licenças, governação clínica e direitos do local", "Validar procura, serviços, compras, cadeia de frio e orçamento", "Definir o calendário após confirmar aprovações e financiamento"] },
      waterdesco: { objectives: ["Expandir redes de água potável em áreas mal servidas", "Construir sistemas resilientes de saneamento e águas residuais", "Promover práticas hídricas resilientes ao clima", "Desenvolver capacidade comunitária para gerir os sistemas"], impact: ["Volume diário de projeto (litros)", "Equivalente a 50 litros por pessoa e dia"], milestones: ["Conciliar configurações e beneficiários", "Concluir estudos de água, local, procura, tarifas e licenças", "Definir compras, financiamento, operação e manutenção"] },
    },
    zh: {
      agridesco: { objectives: ["将小农户组织为生产合作社", "提供种子和肥料投入信贷，并在收获时偿还", "部署共享机械化设备", "建设玉米、木薯和大豆的仓储及加工能力"], impact: ["计划纳入的农户（目标）", "计划复耕的公顷数（目标）", "计划服务的村庄（目标）", "预计小农户收入增幅"], milestones: ["确认项目实体、土地、参与农户及基线数据", "验证试点、需求、承购、经济性及保障措施", "审查试点证据后确定可融资的推广方案"] },
      investdesco: { objectives: ["将恩东巴港和卡森加港开发为物流基础设施", "发展拟议的矿业投资支柱", "与开发性金融机构设计合资及混合融资", "发展工业园区和分布式可再生能源"], impact: ["第一阶段融资目标（百万美元）", "预计2035年前新增岗位"], milestones: ["确认项目权利、发起方、交易对手及权限", "验证可行性、需求、保障措施、成本及顺序", "确定项目资本结构及获批接洽条款"] },
      phardesco: { objectives: ["在姆布吉马伊启动首个 Pharmalab 中心", "中期计划扩展至10个以上中心", "建设符合GMP的本地仿制药生产单元", "成立 Phardesco Academy 培训医疗人员"], impact: ["2035年前计划建设的中心", "启动融资目标（百万美元）"], milestones: ["确认实体、许可路径、临床治理及场地权利", "验证需求、服务、采购、冷链及试点预算", "批准及融资确认后确定启动时间表"] },
      waterdesco: { objectives: ["向服务不足地区扩展饮用水网络", "建设有韧性的污水与卫生系统", "推广气候适应型水循环做法", "加强社区长期管理能力"], impact: ["每日设计供水量（升）", "按每人每日50升计算的等效人数"], milestones: ["统一网络方案及受益人口假设", "完成水源、场址、需求、收费及许可研究", "确定采购、融资、运营及维护方案"] },
    },
  }[locale];
  const geography = {
    es: { agridesco: ["Gran Kasai, RDC — Kasai, Kasai Central, Kasai Oriental, Sankuru y Lomami"], investdesco: ["RDC — corredores del río Kasai y el lago Mweru", "Enlaces comerciales hacia Zambia y Angola"], phardesco: ["Gran Kasai, RDC — primer centro previsto en Mbuji-Mayi", "Expansión nacional propuesta para 2035"], waterdesco: ["Gran Kasai, RDC"] },
    pt: { agridesco: ["Grande Kasai, RDC — Kasai, Kasai Central, Kasai Oriental, Sankuru e Lomami"], investdesco: ["RDC — corredores do rio Kasai e do lago Mweru", "Ligações comerciais à Zâmbia e Angola"], phardesco: ["Grande Kasai, RDC — primeiro centro previsto em Mbuji-Mayi", "Expansão nacional proposta até 2035"], waterdesco: ["Grande Kasai, RDC"] },
    zh: { agridesco: ["刚果民主共和国大开赛地区，包括开赛、中开赛、东开赛、桑库鲁和洛马米省"], investdesco: ["刚果民主共和国开赛河与姆韦鲁湖走廊", "通往赞比亚和安哥拉的贸易联系"], phardesco: ["刚果民主共和国大开赛地区，首个中心拟设于姆布吉马伊", "计划于2035年前扩展至全国"], waterdesco: ["刚果民主共和国大开赛地区"] },
  }[locale];
  const translated: Record<string, PillarText> = {};
  for (const pillar of PILLARS) {
    translated[pillar.slug] = {
      ...pillar,
      shortName: words[pillar.shortName as keyof typeof words] || pillar.shortName,
      tagline: locale === "es" ? `Área propuesta de ${words[pillar.shortName as keyof typeof words] || pillar.shortName}; su alcance y ejecución están sujetos a diligencia.` : locale === "pt" ? `Área proposta de ${words[pillar.shortName as keyof typeof words] || pillar.shortName}; o âmbito e a execução estão sujeitos a diligência.` : `${words[pillar.shortName as keyof typeof words] || pillar.shortName}拟议业务领域；范围与实施仍需尽职调查。`,
      summary: locale === "es" ? `Presentamos ${pillar.name} como una línea de negocio de DESCO. Antes de avanzar, exigimos verificar derechos, permisos, datos operativos, financiación y calendario.` : locale === "pt" ? `Apresentamos a ${pillar.name} como uma área de negócio da DESCO. Antes de avançar, exigimos a verificação de direitos, licenças, dados operacionais, financiamento e calendário.` : `我们将 ${pillar.name} 作为 DESCO 业务板块展示。推进前，我们要求核实相关权利、许可、运营数据、融资及时间表。`,
      thesis: locale === "es" ? `Desarrollamos ${pillar.name} para responder a una necesidad regional identificada. La tesis, sus supuestos y la capacidad de ejecución requieren validación independiente.` : locale === "pt" ? `Desenvolvemos a ${pillar.name} para responder a uma necessidade regional identificada. A tese, os pressupostos e a capacidade de execução exigem validação independente.` : `我们发展 ${pillar.name} 以回应已识别的区域需求。其投资逻辑、假设及执行能力仍须独立验证。`,
      marketOpportunity: locale === "es" ? `Nuestras cifras de mercado requieren validación. La demanda, los precios, la competencia y las hipótesis de ejecución siguen sujetos a diligencia.` : locale === "pt" ? `Os nossos dados de mercado exigem validação. A procura, os preços, a concorrência e os pressupostos de execução continuam sujeitos a diligência.` : "我们的市场数据仍须验证。需求、定价、竞争及执行假设仍须尽职调查。",
      geography: geography[pillar.slug as keyof typeof geography],
      objectives: content[pillar.slug as keyof typeof content].objectives,
      impact: pillar.impact.map((i, index) => ({ ...i, label: content[pillar.slug as keyof typeof content].impact[index] })),
      milestones: pillar.milestones.map((m, index) => ({ ...m, label: content[pillar.slug as keyof typeof content].milestones[index] })),
    };
  }
  return translated;
}

const routeText = {
  en: {
    metadataTitle: "Our business pillars — DESCO Compass", metadataDescription: "Our four DESCO Global business pillars, their investment focus and explicit diligence qualifications.",
    vision: "Desco Global · Four business areas", heroTitle: "Agriculture, infrastructure, healthcare and water.", heroBody: "We prepare each proposed project separately in the Democratic Republic of the Congo. Capital requirements, rights, scope and delivery dates must be established at project level before investor engagement.", partner: "Partner with us", opportunities: "Review current preparation files",
    who: "Who we are", profile: "Our profile and proposed operating model", profileBody: "We are developing an integrated group of businesses in the Democratic Republic of the Congo. Before investor reliance, we require approved evidence of operating status, corporate structure, governance, audit standards and environmental and social systems.",
    fit: "How this fits together", roles: [["Desco Global", "The proposed group sponsor and developer. Its legal role, ownership and authority should be confirmed for each project."], ["DESCO Compass", "A private-beta platform for reviewing public project briefings and requesting controlled information access."], ["The four pillars", "Agridesco, Investdesco, Phardesco and Waterdesco are four proposed business areas described in sponsor materials."], ["Project sponsors", "The party responsible for a listing's content. Its identity, legal role and authority should be confirmed."], ["Investors", "Professional investors can review public information. Account creation, workspace approval and project-specific access are separate controlled steps."], ["Advisors", "Advisors may support investors or sponsors in review and diligence; no affiliation is implied."]],
    region: "Why the Grand Kasai region", regionTitle: "Regional context and infrastructure constraints", regionBody: "We see agricultural and mineral potential alongside significant transport constraints. Proposed port routes, demand and delivery remain subject to diligence.", drc: "Why the DRC", drcTitle: "Our market context", drcBody: "Our current materials identify population growth, food imports, water access and healthcare gaps as the basis for the four pillars.", marketQualifier: "Market figures are drawn from DESCO Global materials. We have not yet independently verified every trade, demographic, healthcare or benchmark figure cited.",
    approach: "Our approach", approachTitle: "Proposed project-preparation process", steps: [["Confirm project rights", "Document ownership, concessions, permits, counterparties and authority to transact."], ["Prepare the evidence base", "Organise technical, financial, legal, environmental and commercial information for review."], ["Structure the financing process", "Define the capital requirement, proposed instrument, governance terms and due-diligence pathway."]],
    stats: ["Proposed business areas", "Current preparation files", "Supported languages", "People equivalent at 50 litres per day"], statsQualifier: "The water equivalent is derived from the sponsor’s 45 million-litre daily design target; the technical design and beneficiary assumptions remain unverified.",
    integrated: "Integrated pillars", four: "Four proposed business areas", closing: "Review the proposed programme, its evidence and its outstanding diligence requirements.",
    detail: { all: "All pillars", breadcrumb: "Breadcrumb", executive: "Executive summary", thesis: "Investment thesis", market: "Market opportunity", objectives: "Strategic objectives", objectivesNote: "Planned goals — not yet completed or independently verified.", timeline: "Preparation sequence", impact: "Impact metrics", impactNote: "Figures come from sponsor materials and have not been independently verified. Targets, plans and projections are forward estimates, not measured results.", geography: "Geographic coverage", mapNote: "Regions shown are proposed operating geographies; project-specific rights and delivery require confirmation.", engage: "Engage with", engageBody: "Public opportunity information is available through Compass. Account creation, workspace approval and project-specific access remain separate controlled steps.", signIn: "Discuss this business area", others: "Explore other pillars", learn: "Learn more", inProgress: "Pending evidence" },
    legal: { metadataTitle: "Legal and security — DESCO Compass", metadataDescription: "Current platform, privacy, cookie, terms, security, investment-risk and verification disclosures.", title: "Legal and security", intro: "This page states the current legal and security position. Items marked pending review are not approved policy.", pending: "Pending DESCO review", questions: "Questions, corrections or complaints:", sections: [
      ["Platform status", "DESCO Compass is in private beta. Public opportunity information may reference real projects, but the site is not a securities offer, trading venue or investment recommendation and does not execute investment transactions. Jurisdiction-specific restrictions may apply."],
      ["Privacy notice", "A complete privacy notice covering data collected, purposes, legal basis, retention, rights and cross-border transfers is pending legal review. Do not submit sensitive or confidential information.", true],
      ["Cookie notice", "Compass uses session and language-preference cookies. A complete cookie inventory and any required consent mechanism are pending legal review.", true],
      ["Terms of use", "Binding terms covering platform use, user obligations, liability and dispute resolution are pending legal review.", true],
      ["Security overview", "Account creation and email access activate only when the required mail and legal configuration is present. Workspace and project access require separate server-side authorisation. A complete security disclosure is pending review."],
      ["Investment risk", "DESCO Compass does not guarantee project performance, returns or exits. Project information may be sponsor-provided and unverified. Users must complete independent legal, financial, tax, technical, ESG and commercial diligence."],
      ["Verification methodology", "A review label applies only to the stated item and scope. It does not verify every project claim or constitute investment approval."],
      ["Related-party review", "A public listing identifies a DESCO ownership, development, mandate, facilitation or advisory relationship when recorded in the approved source manifest. Related opportunities follow the same disclosure fields and publication controls, and a DESCO review remains internal rather than independent. Any compensation and additional conflict controls require contract-level confirmation before investor engagement."],
      ["Operating and regulatory scope", "DESCO Compass publishes structured project information, supports mandate screening and manages permission requests. It does not hold investor funds, execute transactions or provide investment recommendations. The contracting entity, domicile and regulatory perimeter must be confirmed before any paid introduction, placement or transaction-linked activity."],
      ["Complaints and reporting", "Report inaccurate listing information, security concerns or conduct complaints to support@desco.global. Reports are routed for review."],
    ] as [string, string, boolean?][] },
  },
};

type RouteText = typeof routeText.en;

function localizeRoute(locale: Exclude<Locale, "en">): RouteText {
  const en = routeText.en;
  const packs = {
    fr: ["Piliers d’activité proposés — DESCO Compass", "Les quatre piliers proposés de DESCO Global, avec les objectifs du promoteur et les réserves de diligence.", "Agriculture, infrastructures, santé et eau.", "Nous préparons chaque projet séparément en RDC. Les besoins en capitaux, les droits, le périmètre et les dates doivent être établis au niveau du projet.", "Mentions légales et sécurité", "Cette page présente la situation juridique et de sécurité actuelle. Les éléments signalés en attente ne sont pas des politiques approuvées."],
    es: ["Pilares de negocio propuestos — DESCO Compass", "Los cuatro pilares propuestos de DESCO Global, con objetivos del promotor y reservas de diligencia.", "Agricultura, infraestructura, salud y agua.", "Preparamos cada proyecto por separado en la RDC. El capital, los derechos, el alcance y las fechas deben establecerse a nivel de proyecto.", "Información legal y seguridad", "Esta página expone la situación jurídica y de seguridad actual. Los elementos pendientes no son políticas aprobadas."],
    pt: ["Pilares de negócio propostos — DESCO Compass", "Os quatro pilares propostos da DESCO Global, com metas do promotor e ressalvas de diligência.", "Agricultura, infraestruturas, saúde e água.", "Preparamos cada projeto separadamente na RDC. O capital, os direitos, o âmbito e as datas devem ser definidos ao nível do projeto.", "Informação jurídica e segurança", "Esta página apresenta a situação jurídica e de segurança atual. Os elementos pendentes não são políticas aprovadas."],
    zh: ["拟议业务支柱 — DESCO Compass", "DESCO Global 的四个拟议业务支柱，包括发起方目标和明确的尽调限定。", "农业、基础设施、医疗健康与水务。", "DESCO Global 材料描述了在刚果民主共和国四个行业开展、规模为7.5亿美元的拟议第一阶段计划。资金需求、范围和交付日期均为发起方目标。", "法律与安全", "本页说明当前法律与安全状态。标记为待审核的内容并非已批准政策。"],
  }[locale];
  const generic = (fr: string, es: string, pt: string, zh: string) => ({ fr, es, pt, zh }[locale]);
  const legalSections = {
    fr: [
      ["Statut de la plateforme", "DESCO Compass est en bêta privée. Les informations publiques peuvent concerner des projets réels, mais le site ne constitue ni une offre de titres, ni une plateforme de négociation, ni une recommandation et n’exécute aucune transaction d’investissement. Des restrictions juridictionnelles peuvent s’appliquer."],
      ["Avis de confidentialité", "Un avis complet couvrant les données collectées, les finalités, la base juridique, la conservation, les droits et les transferts internationaux attend l’examen juridique. Ne transmettez aucune information sensible ou confidentielle.", true],
      ["Avis relatif aux cookies", "Compass utilise des cookies de session et de préférence linguistique. L’inventaire complet et tout mécanisme de consentement requis attendent l’examen juridique.", true],
      ["Conditions d’utilisation", "Les conditions contraignantes relatives à l’utilisation, aux obligations, à la responsabilité et au règlement des litiges attendent l’examen juridique.", true],
      ["Présentation de la sécurité", "La création de compte et l’accès par courriel ne sont activés que lorsque la messagerie et la configuration juridique requises sont présentes. L’espace de travail et l’accès projet exigent des autorisations distinctes côté serveur. La présentation complète de la sécurité attend l’examen."],
      ["Risque d’investissement", "DESCO Compass ne garantit ni la performance, ni le rendement, ni la sortie d’un projet. Les informations peuvent provenir du promoteur sans vérification indépendante. Les utilisateurs doivent effectuer leurs propres diligences juridiques, financières, fiscales, techniques, ESG et commerciales."],
      ["Méthode de vérification", "Une mention de revue s’applique uniquement à l’élément et au périmètre indiqués. Elle ne vérifie pas toutes les affirmations et ne constitue pas une approbation d’investissement."],
      ["Examen des parties liées", "Une fiche publique identifie toute relation de propriété, développement, mandat, facilitation ou conseil avec DESCO enregistrée dans le registre de sources approuvé. Ces opportunités suivent les mêmes champs de divulgation et contrôles de publication ; une revue DESCO reste interne et non indépendante. Toute rémunération et tout contrôle supplémentaire des conflits doivent être confirmés par contrat avant l’échange investisseur."],
      ["Périmètre opérationnel et réglementaire", "DESCO Compass publie des informations structurées, facilite le filtrage selon le mandat et gère les demandes d’autorisation. La plateforme ne détient pas les fonds des investisseurs, n’exécute pas de transactions et ne fournit pas de recommandations d’investissement. L’entité contractante, le domicile et le périmètre réglementaire doivent être confirmés avant toute activité rémunérée d’introduction, de placement ou liée à une transaction."],
      ["Réclamations et signalements", "Signalez les informations inexactes, problèmes de sécurité ou plaintes à support@desco.global. Les signalements sont orientés pour examen."],
    ],
    es: [
      ["Estado de la plataforma", "DESCO Compass está en beta privada. La información pública puede referirse a proyectos reales, pero el sitio no es una oferta de valores, un mercado de negociación ni una recomendación y no ejecuta operaciones de inversión. Pueden aplicarse restricciones jurisdiccionales."],
      ["Aviso de privacidad", "Un aviso completo sobre datos recogidos, fines, base jurídica, conservación, derechos y transferencias internacionales está pendiente de revisión legal. No envíe información sensible o confidencial.", true],
      ["Aviso de cookies", "Compass utiliza cookies de sesión y preferencia de idioma. El inventario completo y cualquier mecanismo de consentimiento requerido están pendientes de revisión legal.", true],
      ["Condiciones de uso", "Las condiciones vinculantes sobre uso, obligaciones, responsabilidad y resolución de conflictos están pendientes de revisión legal.", true],
      ["Resumen de seguridad", "La creación de cuentas y el acceso por correo solo se activan cuando están configurados el servicio de correo y los requisitos legales. El espacio de trabajo y cada proyecto requieren autorizaciones separadas en el servidor. El informe completo de seguridad está pendiente."],
      ["Riesgo de inversión", "DESCO Compass no garantiza resultados, rendimientos ni salidas. La información puede proceder del promotor sin verificación independiente. Los usuarios deben realizar diligencia jurídica, financiera, fiscal, técnica, ESG y comercial propia."],
      ["Metodología de verificación", "Una etiqueta de revisión se aplica únicamente al elemento y alcance indicados. No verifica todas las afirmaciones ni constituye aprobación de inversión."],
      ["Revisión de partes vinculadas", "Una ficha pública identifica cualquier relación de propiedad, desarrollo, mandato, facilitación o asesoramiento con DESCO registrada en el manifiesto de fuentes aprobado. Estas oportunidades siguen los mismos campos de divulgación y controles de publicación; una revisión DESCO sigue siendo interna y no independiente. Toda remuneración y control adicional de conflictos debe confirmarse por contrato antes del contacto con inversores."],
      ["Alcance operativo y regulatorio", "DESCO Compass publica información estructurada, facilita la selección según el mandato y gestiona solicitudes de permisos. No custodia fondos, ejecuta operaciones ni formula recomendaciones de inversión. La entidad contratante, el domicilio y el perímetro regulatorio deben confirmarse antes de cualquier actividad remunerada de introducción, colocación o vinculada a una operación."],
      ["Reclamaciones y reportes", "Informe de datos inexactos, problemas de seguridad o conducta a support@desco.global. Los reportes se remiten para revisión."],
    ],
    pt: [
      ["Estado da plataforma", "A DESCO Compass está em beta privada. A informação pública pode referir projetos reais, mas o site não é uma oferta de valores mobiliários, plataforma de negociação ou recomendação e não executa operações de investimento. Podem aplicar-se restrições jurisdicionais."],
      ["Aviso de privacidade", "Um aviso completo sobre dados recolhidos, finalidades, base jurídica, retenção, direitos e transferências internacionais aguarda revisão jurídica. Não envie informação sensível ou confidencial.", true],
      ["Aviso de cookies", "A Compass utiliza cookies de sessão e preferência linguística. O inventário completo e qualquer mecanismo de consentimento necessário aguardam revisão jurídica.", true],
      ["Termos de utilização", "Os termos vinculativos sobre utilização, obrigações, responsabilidade e resolução de litígios aguardam revisão jurídica.", true],
      ["Visão geral de segurança", "A criação de contas e o acesso por correio só são ativados quando o serviço de correio e os requisitos jurídicos estão configurados. O espaço de trabalho e cada projeto exigem autorizações separadas no servidor. A divulgação completa de segurança está pendente."],
      ["Risco de investimento", "A DESCO Compass não garante desempenho, retornos ou saídas. A informação pode ser fornecida pelo promotor sem verificação independente. Os utilizadores devem realizar diligência jurídica, financeira, fiscal, técnica, ESG e comercial própria."],
      ["Metodologia de verificação", "Uma etiqueta de revisão aplica-se apenas ao elemento e âmbito indicados. Não verifica todas as afirmações nem constitui aprovação de investimento."],
      ["Análise de partes relacionadas", "Uma ficha pública identifica qualquer relação de propriedade, desenvolvimento, mandato, facilitação ou consultoria com a DESCO registada no manifesto de fontes aprovado. Estas oportunidades seguem os mesmos campos de divulgação e controlos de publicação; uma análise DESCO continua interna e não independente. Qualquer remuneração e controlo adicional de conflitos devem ser confirmados por contrato antes do contacto com investidores."],
      ["Âmbito operacional e regulamentar", "A DESCO Compass publica informação estruturada, apoia a seleção segundo o mandato e gere pedidos de permissão. Não detém fundos, executa transações ou fornece recomendações de investimento. A entidade contratante, o domicílio e o perímetro regulamentar devem ser confirmados antes de qualquer atividade remunerada de introdução, colocação ou ligada a uma transação."],
      ["Reclamações e denúncias", "Comunique informação inexata, problemas de segurança ou conduta a support@desco.global. As comunicações são encaminhadas para análise."],
    ],
    zh: [
      ["平台状态", "DESCO Compass 处于私人测试阶段。公开信息可能涉及真实项目，但本网站不构成证券要约、交易场所或投资建议，也不执行投资交易。不同司法管辖区的限制可能适用。"],
      ["隐私声明", "关于收集的数据、用途、法律依据、保存期限、个人权利及跨境传输的完整隐私声明尚待法律审核。请勿提交敏感或机密信息。", true],
      ["Cookie 声明", "Compass 使用会话及语言偏好 Cookie。完整清单及任何必要的同意机制尚待法律审核。", true],
      ["使用条款", "关于平台使用、用户义务、责任及争议解决的约束性条款尚待法律审核。", true],
      ["安全概述", "只有在邮件服务及所需法律配置完成后，账户创建和邮件访问才会启用。工作区及特定项目访问须经过独立的服务器端授权。完整安全披露尚待审核。"],
      ["投资风险", "DESCO Compass 不保证项目表现、回报或退出。项目信息可能由发起方提供且未经独立核实。用户须自行开展法律、财务、税务、技术、ESG及商业尽调。"],
      ["核实方法", "审核标签仅适用于其注明的项目和范围，并不核实所有项目主张，也不构成投资批准。"],
      ["关联方审查", "如经批准的来源清单记录了 DESCO 的所有权、开发、授权、协助或顾问关系，公开项目页面将予以标明。关联项目适用相同的披露字段和发布控制；DESCO 审查仍属内部审查，不构成独立核实。任何报酬安排及额外利益冲突控制，须在投资者接洽前通过合同确认。"],
      ["运营及监管范围", "DESCO Compass 发布结构化项目信息，支持按投资授权筛选，并管理权限申请。平台不持有投资者资金、不执行交易，也不提供投资建议。开展任何收费的介绍、配售或交易相关活动前，须确认签约主体、注册地及监管边界。"],
      ["投诉与举报", "如需举报不准确的项目资料、安全问题或行为投诉，请联系 support@desco.global。举报将转交审核。"],
    ],
  }[locale] as [string, string, boolean?][];
  return {
    ...en,
    metadataTitle: packs[0], metadataDescription: packs[1], heroTitle: packs[2], heroBody: packs[3],
    partner: generic("Nous contacter", "Contactar", "Contactar", "联系我们"), opportunities: generic("Voir les opportunités publiques", "Ver oportunidades públicas", "Ver oportunidades públicas", "查看公开机会"),
    who: generic("Qui sommes-nous", "Quiénes somos", "Quem somos", "关于我们"), profile: generic("Profil du promoteur et modèle proposé", "Perfil del promotor y modelo propuesto", "Perfil do promotor e modelo proposto", "发起方概况及拟议运营模式"),
    profileBody: generic("Les documents du promoteur décrivent un groupe basé en Afrique du Sud. Son statut opérationnel, sa structure, sa gouvernance, ses audits et ses systèmes environnementaux et sociaux exigent des preuves approuvées.", "Los materiales describen un grupo con sede en Sudáfrica. Su situación operativa, estructura, gobierno, auditoría y sistemas ambientales y sociales requieren pruebas aprobadas.", "Os materiais descrevem um grupo sediado na África do Sul. O estado operacional, a estrutura, a governação, a auditoria e os sistemas ambientais e sociais exigem provas aprovadas.", "发起方材料描述了一个总部位于南非的集团。其运营状态、公司结构、治理、审计及环境和社会体系均须有经批准的证据。"),
    fit: generic("Organisation proposée", "Estructura propuesta", "Estrutura proposta", "拟议架构"),
    roles: [
      ["Desco Global", generic("Promoteur et développeur proposé du groupe. Son rôle juridique, sa propriété et son pouvoir doivent être confirmés pour chaque projet.", "Promotor y desarrollador propuesto del grupo. Su función jurídica, propiedad y autoridad deben confirmarse para cada proyecto.", "Promotor e promotor imobiliário proposto do grupo. O papel jurídico, a propriedade e a autoridade devem ser confirmados em cada projeto.", "拟议集团发起方及开发方。其法律角色、所有权和交易权限须按项目确认。")],
      ["DESCO Compass", generic("Plateforme en bêta privée destinée à examiner les présentations publiques et à demander un accès contrôlé.", "Plataforma en beta privada para revisar fichas públicas y solicitar acceso controlado.", "Plataforma em beta privada para analisar fichas públicas e solicitar acesso controlado.", "用于审查公开项目简介及申请受控信息访问的私人测试平台。")],
      [generic("Les quatre piliers", "Los cuatro pilares", "Os quatro pilares", "四个支柱"), generic("Agridesco, Investdesco, Phardesco et Waterdesco sont quatre domaines proposés dans les documents du promoteur.", "Agridesco, Investdesco, Phardesco y Waterdesco son cuatro áreas propuestas en los materiales del promotor.", "Agridesco, Investdesco, Phardesco e Waterdesco são quatro áreas propostas nos materiais do promotor.", "Agridesco、Investdesco、Phardesco 和 Waterdesco 是发起方材料中的四个拟议业务领域。")],
      [generic("Promoteurs de projets", "Promotores de proyectos", "Promotores de projetos", "项目发起方"), generic("La partie responsable du contenu d’une fiche. Son identité, son rôle juridique et son pouvoir doivent être confirmés.", "La parte responsable del contenido de una ficha. Deben confirmarse su identidad, función jurídica y autoridad.", "A parte responsável pelo conteúdo de uma ficha. A identidade, o papel jurídico e a autoridade devem ser confirmados.", "对项目资料负责的一方。其身份、法律角色和权限须予确认。")],
      [generic("Investisseurs", "Inversores", "Investidores", "投资者"), generic("Les investisseurs professionnels peuvent examiner les informations publiques. La création de compte, l’approbation de l’espace et l’accès projet sont des étapes distinctes.", "Los inversores profesionales pueden revisar la información pública. La creación de cuenta, la aprobación del espacio y el acceso al proyecto son pasos separados.", "Os investidores profissionais podem analisar a informação pública. A criação de conta, a aprovação do espaço e o acesso ao projeto são etapas separadas.", "专业投资者可审阅公开信息。账户创建、工作区批准及特定项目访问为独立步骤。")],
      [generic("Conseillers", "Asesores", "Consultores", "顾问"), generic("Ils peuvent accompagner l’examen et la diligence; aucune affiliation n’est implicite.", "Pueden apoyar la revisión y la diligencia; no se implica afiliación.", "Podem apoiar a análise e a diligência; não se presume qualquer afiliação.", "可协助审查和尽调；不暗示任何关联关系。")],
    ],
    region: generic("Pourquoi le Grand Kasaï", "Por qué el Gran Kasai", "Porquê o Grande Kasai", "为何选择大开赛地区"), regionTitle: generic("Contexte régional et contraintes d’infrastructure", "Contexto regional y limitaciones de infraestructura", "Contexto regional e limitações de infraestrutura", "区域背景与基础设施限制"),
    regionBody: generic("Les documents du promoteur décrivent un potentiel agricole et minier ainsi que des contraintes de transport. Les itinéraires portuaires, la demande et la réalisation restent à vérifier.", "Los materiales describen potencial agrícola y minero y limitaciones de transporte. Las rutas portuarias, la demanda y la ejecución siguen sujetas a diligencia.", "Os materiais descrevem potencial agrícola e mineiro e limitações de transporte. As rotas portuárias, a procura e a execução continuam sujeitas a diligência.", "发起方材料描述了农业和矿产潜力以及运输限制。港口路线、需求和交付仍须尽职调查。"),
    drc: generic("Pourquoi la RDC", "Por qué la RDC", "Porquê a RDC", "为何选择刚果民主共和国"), drcTitle: generic("Contexte de marché décrit par le promoteur", "Contexto de mercado descrito por el promotor", "Contexto de mercado descrito pelo promotor", "发起方所述市场背景"), drcBody: generic("Les documents citent la population, les importations alimentaires, l’accès à l’eau et les besoins de santé comme fondement des quatre piliers.", "Los materiales citan población, importaciones alimentarias, acceso al agua y carencias sanitarias como base de los cuatro pilares.", "Os materiais citam população, importações alimentares, acesso à água e carências de saúde como base dos quatro pilares.", "发起方材料将人口、食品进口、用水和医疗缺口作为四个拟议支柱的依据。"),
    marketQualifier: generic("Les chiffres proviennent des documents du promoteur et n’ont pas été vérifiés indépendamment par Compass.", "Las cifras proceden de materiales del promotor y no han sido verificadas de forma independiente por Compass.", "Os dados provêm de materiais do promotor e não foram verificados de forma independente pela Compass.", "相关数据来自发起方材料，Compass 尚未进行独立核实。"),
    approach: generic("Notre démarche", "Nuestro enfoque", "A nossa abordagem", "方法"), approachTitle: generic("Processus proposé de préparation des projets", "Proceso propuesto de preparación de proyectos", "Processo proposto de preparação de projetos", "拟议项目准备流程"),
    steps: [
      [generic("Confirmer les droits du projet", "Confirmar los derechos del proyecto", "Confirmar os direitos do projeto", "确认项目权利"), generic("Documenter la propriété, les concessions, les permis, les contreparties et le pouvoir de conclure.", "Documentar propiedad, concesiones, permisos, contrapartes y autoridad para contratar.", "Documentar propriedade, concessões, licenças, contrapartes e autoridade para contratar.", "记录所有权、特许权、许可、交易对手及交易权限。")],
      [generic("Préparer les preuves", "Preparar las pruebas", "Preparar as provas", "准备证据基础"), generic("Organiser les informations techniques, financières, juridiques, environnementales et commerciales.", "Organizar información técnica, financiera, jurídica, ambiental y comercial.", "Organizar informação técnica, financeira, jurídica, ambiental e comercial.", "整理技术、财务、法律、环境和商业信息以供审查。")],
      [generic("Structurer le financement", "Estructurar la financiación", "Estruturar o financiamento", "设计融资流程"), generic("Définir le besoin en capital, l’instrument proposé, la gouvernance et le parcours de diligence.", "Definir el capital, el instrumento propuesto, el gobierno y el proceso de diligencia.", "Definir o capital, o instrumento proposto, a governação e o processo de diligência.", "明确资金需求、拟议工具、治理条款及尽调路径。")],
    ],
    integrated: generic("Piliers intégrés", "Pilares integrados", "Pilares integrados", "综合支柱"), four: generic("Quatre domaines d’activité proposés", "Cuatro áreas de negocio propuestas", "Quatro áreas de negócio propostas", "四个拟议业务领域"), closing: generic("Examiner le programme proposé, ses preuves et les diligences encore requises.", "Revisar el programa propuesto, sus pruebas y la diligencia pendiente.", "Analisar o programa proposto, as provas e a diligência pendente.", "审查拟议计划、现有证据及尚待完成的尽调。"),
    stats: [generic("Domaines d’activité proposés", "Áreas de negocio propuestas", "Áreas de negócio propostas", "拟议业务领域"), generic("Dossiers en préparation", "Expedientes en preparación", "Dossiês em preparação", "准备中的项目文件"), generic("Langues prises en charge", "Idiomas disponibles", "Idiomas disponíveis", "支持语言"), generic("Équivalent à 50 litres par personne et par jour", "Equivalente a 50 litros por persona y día", "Equivalente a 50 litros por pessoa e dia", "按每人每日50升计算的等效覆盖人数")],
    statsQualifier: generic("L’équivalent d’eau découle de l’objectif de conception de 45 millions de litres par jour; la conception et les hypothèses restent à vérifier.", "El equivalente de agua se deriva del objetivo de diseño de 45 millones de litros diarios; el diseño y los supuestos siguen sin verificar.", "O equivalente de água deriva da meta de projeto de 45 milhões de litros por dia; o projeto e os pressupostos continuam por verificar.", "供水等效人数按每日4500万升设计目标计算，技术设计及受益人假设仍待核实。"),
    detail: { ...en.detail, all: generic("Tous les piliers", "Todos los pilares", "Todos os pilares", "全部支柱"), breadcrumb: generic("Fil d’Ariane", "Migas de pan", "Navegação estrutural", "面包屑导航"), executive: generic("Synthèse", "Resumen ejecutivo", "Resumo executivo", "执行摘要"), thesis: generic("Thèse d’investissement", "Tesis de inversión", "Tese de investimento", "投资逻辑"), market: generic("Opportunité de marché", "Oportunidad de mercado", "Oportunidade de mercado", "市场机会"), objectives: generic("Objectifs stratégiques", "Objetivos estratégicos", "Objetivos estratégicos", "战略目标"), objectivesNote: generic("Objectifs prévus, non réalisés ni vérifiés indépendamment.", "Objetivos previstos, aún no realizados ni verificados.", "Objetivos planeados, ainda não realizados nem verificados.", "计划目标，尚未完成或独立核实。"), timeline: generic("Calendrier et jalons", "Calendario e hitos", "Calendário e marcos", "时间表与里程碑"), impact: generic("Indicateurs d’impact", "Indicadores de impacto", "Indicadores de impacto", "影响指标"), impactNote: generic("Chiffres issus des documents du promoteur; objectifs et projections non vérifiés.", "Cifras de materiales del promotor; objetivos y proyecciones no verificados.", "Dados dos materiais do promotor; metas e projeções não verificadas.", "数据来自发起方材料；目标和预测尚未经独立核实。"), geography: generic("Couverture géographique", "Cobertura geográfica", "Cobertura geográfica", "地域范围"), mapNote: generic("Les zones indiquées sont proposées; les droits propres à chaque projet doivent être confirmés.", "Las zonas son propuestas; deben confirmarse los derechos de cada proyecto.", "As áreas são propostas; os direitos de cada projeto devem ser confirmados.", "所列区域为拟议范围；具体项目权利仍须确认。"), engage: generic("Échanger avec", "Contactar con", "Contactar", "联系"), engageBody: generic("Les informations publiques sont disponibles sur Compass. La création de compte, l’approbation de l’espace et l’accès projet restent des étapes distinctes.", "La información pública está disponible en Compass. La creación de cuenta, la aprobación del espacio y el acceso al proyecto siguen siendo pasos separados.", "A informação pública está disponível na Compass. A criação de conta, a aprovação do espaço e o acesso ao projeto continuam a ser etapas separadas.", "Compass 提供公开信息。账户创建、工作区批准及特定项目访问仍为独立步骤。"), signIn: generic("Ouvrir la page d’accès", "Abrir página de acceso", "Abrir página de acesso", "打开访问页面"), others: generic("Découvrir les autres piliers", "Explorar otros pilares", "Explorar outros pilares", "查看其他支柱"), learn: generic("En savoir plus", "Más información", "Saber mais", "了解更多"), inProgress: generic("Prévu", "Previsto", "Planeado", "计划") },
    legal: { ...en.legal, metadataTitle: packs[4], metadataDescription: generic("Divulgations actuelles sur la plateforme, la confidentialité, les cookies, les conditions, la sécurité et les risques.", "Información actual sobre plataforma, privacidad, cookies, condiciones, seguridad y riesgos.", "Informação atual sobre plataforma, privacidade, cookies, termos, segurança e riscos.", "平台、隐私、Cookie、条款、安全及投资风险的当前披露。"), title: packs[4], intro: packs[5], pending: generic("Examen DESCO en attente", "Pendiente de revisión DESCO", "Revisão DESCO pendente", "待 DESCO 审核"), questions: generic("Questions, corrections ou réclamations :", "Preguntas, correcciones o reclamaciones:", "Questões, correções ou reclamações:", "问题、更正或投诉："), sections: legalSections },
  };
}

export function getPillarsLegal(locale: Locale) {
  const text: RouteText = locale === "en" ? routeText.en : localizeRoute(locale);
  const pillarText: Record<string, PillarText> = locale === "en" ? enPillars : locale === "fr" ? shared.fr : locale === "es" ? esPillars : locale === "pt" ? ptPillars : zhPillars;
  return {
    ...text,
    pillars: PILLARS.map((pillar) => ({ ...pillar, ...pillarText[pillar.slug] })),
  };
}
