export type ProjectDocumentSource = {
  listingId: string;
  sourceLibrary?: "desco_archive" | "google_drive";
  sourceRef: string;
  name: string;
  folder: string;
  documentType: string;
  evidenceCategory: string;
  issuer: string;
  sourceDate?: string;
  version?: string;
  language?: string;
  visibility: "restricted" | "internal";
  reviewNote: string;
};

// Canonical source selection from the supplied DESCO Global folders.
// Paths are relative to DESCO_SOURCE_ROOT and are never shown publicly.
// Contracts, financial assumptions and technical records remain restricted.
export const projectDocumentSources: ProjectDocumentSource[] = [
  {
    listingId: "port-de-ndomba",
    sourceRef: "InvestDesco/Port de Ndomba/DRC_Ports_Business_Plan_20260206210055.pdf",
    name: "DRC Ports Business Plan",
    folder: "1. Investment materials",
    documentType: "business_plan",
    evidenceCategory: "commercial_and_financial",
    issuer: "Desco Global",
    sourceDate: "2026-02-06",
    version: "2026-02-06",
    visibility: "restricted",
    reviewNote: "Combined ports plan. Ndomba and Kasenga assumptions require project-level reconciliation.",
  },
  {
    listingId: "port-de-ndomba",
    sourceRef: "InvestDesco/Port de Ndomba/port_ndomba_investment_memorandum_20260120182757.pptx",
    name: "Port de Ndomba Investment Memorandum",
    folder: "1. Investment materials",
    documentType: "investment_memorandum",
    evidenceCategory: "commercial_and_financial",
    issuer: "Desco Global",
    sourceDate: "2026-01-20",
    version: "2026-01-20",
    visibility: "restricted",
    reviewNote: "Sponsor material; assumptions and rights remain subject to diligence.",
  },
  {
    listingId: "port-de-ndomba",
    sourceRef: "InvestDesco/Port de Ndomba/port_ndomba_visualisations_20251214161948.pdf",
    name: "Port de Ndomba Concept Visualisations",
    folder: "4. Design and delivery",
    documentType: "concept_visualisations",
    evidenceCategory: "technical_concept",
    issuer: "Desco Global",
    sourceDate: "2025-12-14",
    version: "2025-12-14",
    visibility: "restricted",
    reviewNote: "Concept imagery only; it is not evidence of existing infrastructure or construction progress.",
  },
  {
    listingId: "port-de-kasenga",
    sourceRef: "InvestDesco/Port de Ndomba/DRC_Ports_Business_Plan_20260206210055.pdf",
    name: "DRC Ports Business Plan — Kasenga Extract",
    folder: "1. Investment materials",
    documentType: "business_plan",
    evidenceCategory: "commercial_and_financial",
    issuer: "Desco Global",
    sourceDate: "2026-02-06",
    version: "2026-02-06",
    visibility: "restricted",
    reviewNote: "Combined programme source. A separate Kasenga dossier, demand study and rights pack were not located.",
  },
  {
    listingId: "comicordia-mining",
    sourceRef: "InvestDesco/Comicordia/Decks & Business Plans/investdesco_comicordia_mining_presentation_20260206_final.pdf",
    name: "Comicordia Mining Investment Presentation",
    folder: "1. Investment materials",
    documentType: "investor_deck",
    evidenceCategory: "commercial_and_financial",
    issuer: "Comicordia / Desco Global",
    sourceDate: "2026-02-06",
    version: "final-2026-02-06",
    visibility: "restricted",
    reviewNote: "Sponsor presentation; production and economic claims require source-level verification.",
  },
  {
    listingId: "comicordia-mining",
    sourceRef: "InvestDesco/Comicordia/Technical & Geology/Rapp_géol_PR13578_Luiza (1).pdf",
    name: "PR 13578 Luiza Geological Report",
    folder: "2. Technical and geology",
    documentType: "geological_report",
    evidenceCategory: "technical",
    issuer: "Project sponsor",
    version: "historical-report",
    language: "fr",
    visibility: "restricted",
    reviewNote: "Historical geology; it must not be described as a current compliant resource or reserve.",
  },
  {
    listingId: "comicordia-mining",
    sourceRef: "InvestDesco/Comicordia/Technical & Geology/Annexe 1-Liste des Coordonnées_DEM- Impression du Certificat (2).pdf",
    name: "Permit Coordinates and Certificate Annex",
    folder: "3. Legal, title and permits",
    documentType: "permit_record",
    evidenceCategory: "title_and_permits",
    issuer: "Project sponsor",
    language: "fr",
    visibility: "restricted",
    reviewNote: "Current standing, ownership and transferability require independent confirmation.",
  },
  {
    listingId: "comicordia-mining",
    sourceRef: "InvestDesco/Comicordia/Technical & Geology/MUSEFU Open Cast Mining AISC (2) (2).pdf",
    name: "Musefu Open-Cast Mining Cost Paper",
    folder: "2. Technical and geology",
    documentType: "cost_study",
    evidenceCategory: "technical_and_financial",
    issuer: "Project sponsor",
    visibility: "restricted",
    reviewNote: "Concept-level cost paper; assumptions require independent technical and financial review.",
  },
  {
    listingId: "comicordia-mining",
    sourceLibrary: "google_drive",
    sourceRef: "Desco Global/Projects/Mining/Comicordia Cooperative/LUIZA_PROJET_D'APPUI_A_LA_PRODUCTION[2].docx",
    name: "Luiza Artisanal Production Support Project",
    folder: "1. Investment materials",
    documentType: "historical_project_plan",
    evidenceCategory: "sponsor_and_project_history",
    issuer: "COMICORDIA/Luiza",
    sourceDate: "2022-06-01",
    version: "June 2022",
    language: "fr",
    visibility: "restricted",
    reviewNote: "Historical sponsor plan. Legal standing, grades, production history and proposed operating structure require current independent verification.",
  },
  {
    listingId: "comicordia-agri",
    sourceRef: "AgriDesco/cpam_agri_desco_business_plan_20260320131042.pptx",
    name: "Agridesco CPAM Business Plan",
    folder: "1. Investment materials",
    documentType: "business_plan",
    evidenceCategory: "commercial_and_impact",
    issuer: "Agridesco",
    sourceDate: "2026-03-20",
    version: "2026-03-20",
    visibility: "restricted",
    reviewNote: "Farmer, land, income and employment figures require dated methodologies and source evidence.",
  },
  {
    listingId: "comicordia-agri",
    sourceRef: "AgriDesco/CPAM_Agri_Desco_IMPROVED.pptx",
    name: "Agridesco CPAM Project Presentation",
    folder: "1. Investment materials",
    documentType: "project_presentation",
    evidenceCategory: "commercial_and_impact",
    issuer: "Agridesco",
    visibility: "restricted",
    reviewNote: "Sponsor deck; programme targets are not project results.",
  },
  {
    listingId: "manioc-plant",
    sourceRef: "AgriDesco/Manioc-Project/Usine de traitement des feuilles de manioc ( pour Jonathan).pdf",
    name: "Cassava Leaf Processing Plant Proposal",
    folder: "1. Investment materials",
    documentType: "business_plan",
    evidenceCategory: "technical_and_financial",
    issuer: "Project sponsor",
    language: "fr",
    visibility: "restricted",
    reviewNote: "Equipment, capacity, shelf-life and unit economics remain sponsor claims pending validation.",
  },
  {
    listingId: "phardesco-mbuji-mayi",
    sourceRef: "PharmaDesco/Phardesco_Expanded_Business_Plan.docx",
    name: "Phardesco Expanded Business Plan",
    folder: "1. Investment materials",
    documentType: "business_plan",
    evidenceCategory: "commercial_and_financial",
    issuer: "Phardesco",
    visibility: "restricted",
    reviewNote: "Licensing, medicine supply, market benchmarks and financial forecasts require supporting evidence.",
  },
  {
    listingId: "phardesco-mbuji-mayi",
    sourceRef: "PharmaDesco/PharmaCong_Pitch_Deck_FR (1).pptx",
    name: "Phardesco French Pitch Deck",
    folder: "1. Investment materials",
    documentType: "investor_deck",
    evidenceCategory: "commercial_and_financial",
    issuer: "Phardesco",
    language: "fr",
    visibility: "restricted",
    reviewNote: "Named potential financiers are not commitments unless supported by written confirmation.",
  },
  {
    listingId: "waterdesco-grand-kasai",
    sourceRef: "Desco Global/Strategy/Copy of Water DesCo. Business Plan_.txt",
    name: "WaterDesco Working Business Plan",
    folder: "1. Investment materials",
    documentType: "working_business_plan",
    evidenceCategory: "technical_and_financial",
    issuer: "Desco Global",
    visibility: "internal",
    reviewNote: "Undated working text with unclear provenance. Not approved investor evidence.",
  },
  {
    listingId: "waterdesco-grand-kasai",
    sourceLibrary: "google_drive",
    sourceRef: "Desco Global/DRC Operations/Tenders DRC /AAOI Construction de la nouvelle usine de traitement eau de Lulua y compris fourn et pose conduites de refoulement et distribution gravitaire... Kananga_0001.pdf",
    name: "Kananga Lulua Water Treatment Plant Tender Notice",
    folder: "3. Public procurement references",
    documentType: "tender_notice",
    evidenceCategory: "public_procurement_reference",
    issuer: "Tendering authority identified in source",
    sourceDate: "2025-12-13",
    language: "fr",
    visibility: "restricted",
    reviewNote: "The tender notice supports the existence of a public procurement opportunity. It does not evidence a DESCO award, mandate, bid acceptance or project ownership.",
  },
  {
    listingId: "waterdesco-grand-kasai",
    sourceLibrary: "google_drive",
    sourceRef: "Desco Global/DRC Operations/Tenders DRC /AAOI Réhabilitation et extension usine de traitement eau Kanyuka à Kananga.pdf",
    name: "Kananga Kanyuka Water Treatment Rehabilitation Tender Notice",
    folder: "3. Public procurement references",
    documentType: "tender_notice",
    evidenceCategory: "public_procurement_reference",
    issuer: "Tendering authority identified in source",
    sourceDate: "2025-12-13",
    language: "fr",
    visibility: "restricted",
    reviewNote: "The tender notice supports the existence of a public procurement opportunity. It does not evidence a DESCO award, mandate, bid acceptance or project ownership.",
  },
  {
    listingId: "waterdesco-grand-kasai",
    sourceLibrary: "google_drive",
    sourceRef: "Desco Global/DRC Operations/Tenders DRC /AAOI Rehabilit et extension de distrib prim sec et tert y compris realisation des BF BP... Kananga.pdf",
    name: "Kananga Water Distribution Network Tender Notice",
    folder: "3. Public procurement references",
    documentType: "tender_notice",
    evidenceCategory: "public_procurement_reference",
    issuer: "Tendering authority identified in source",
    sourceDate: "2025-12-13",
    language: "fr",
    visibility: "restricted",
    reviewNote: "The tender notice supports the existence of a public procurement opportunity. It does not evidence a DESCO award, mandate, bid acceptance or project ownership.",
  },
  {
    listingId: "tilu-pepm-8252",
    sourceRef: "Desco Global/Contracts/Aaide - DescoGlobal - Tilu Mining - Contrat de mandat de courtage minier 06.11.2025.docx",
    name: "Tilu Mining Brokerage Mandate",
    folder: "3. Legal, title and permits",
    documentType: "commercial_mandate",
    evidenceCategory: "transaction_authority",
    issuer: "Tilu Mining / counterparties",
    sourceDate: "2025-11-06",
    version: "2025-11-06",
    language: "fr",
    visibility: "restricted",
    reviewNote: "The mandate does not verify permit standing, ownership, geology or investment readiness.",
  },
  {
    listingId: "tilu-pepm-8252",
    sourceLibrary: "google_drive",
    sourceRef: "Desco Global/Projects/Mining/Tilu Mining/TILU MINING_Preliminary Technical Geochemical Study_v1 (1).pdf",
    name: "Tilu PEPM 8252 Preliminary Technical Geochemical Study",
    folder: "2. Technical and geology",
    documentType: "preliminary_geochemical_study",
    evidenceCategory: "technical",
    issuer: "BUMINCO SARL",
    version: "historical preliminary study",
    language: "en",
    visibility: "restricted",
    reviewNote: "The study reports 2010 soil sampling and geochemical anomalies, then recommends further mapping, trenching and drilling. It does not establish a compliant mineral resource or current permit standing.",
  },
  {
    listingId: "sciress-kolwezi-12423",
    sourceRef: "InvestDesco/Scires Mining/pe12423_scires_mining_investment_20251215090828.pdf",
    name: "Scires PE 12423 Investment Presentation",
    folder: "1. Investment materials",
    documentType: "investor_deck",
    evidenceCategory: "technical_and_financial",
    issuer: "Scires Mining",
    sourceDate: "2025-12-15",
    version: "2025-12-15",
    visibility: "restricted",
    reviewNote: "Sponsor deck; title transfer, technical results and return assumptions require independent review.",
  },
  {
    listingId: "sciress-kolwezi-12423",
    sourceRef: "Desco Global/Contracts/Desco_Global_Letter_of_Intention_Sciress.docx",
    name: "Scires Letter of Intent",
    folder: "3. Legal, title and permits",
    documentType: "letter_of_intent",
    evidenceCategory: "transaction_authority",
    issuer: "Desco Global / Scires",
    visibility: "restricted",
    reviewNote: "Review execution status, parties, scope, conditions and expiry before reliance.",
  },
  {
    listingId: "sciress-kolwezi-12423",
    sourceRef: "Desco Global/Contracts/CONTRAT_DE_MANDAT_DE_COURTAGE_MINIER_Scires version finale_bilingual.docx",
    name: "Scires Mining Brokerage Mandate",
    folder: "3. Legal, title and permits",
    documentType: "commercial_mandate",
    evidenceCategory: "transaction_authority",
    issuer: "Scires / Desco Global",
    version: "final-bilingual",
    language: "bilingual",
    visibility: "restricted",
    reviewNote: "Mandate scope and current authority require legal review.",
  },
  {
    listingId: "energulf-lotshi-block",
    sourceRef: "InvestDesco/Energulf/EnerGulf Prospective Final-DM 31122010 Lotshi (2).pdf",
    name: "EnerGulf Lotshi Prospectivity Report",
    folder: "2. Technical and geology",
    documentType: "technical_report",
    evidenceCategory: "technical",
    issuer: "EnerGulf",
    sourceDate: "2010-12-31",
    version: "2010-12-31",
    visibility: "restricted",
    reviewNote: "Historical prospectivity is not a current reserve, discovery or operating result.",
  },
  {
    listingId: "energulf-lotshi-block",
    sourceLibrary: "google_drive",
    sourceRef: "Desco Global/Projects/Mining/Desco Petroleum/EnerGulf/Business Plan EnerGulf.pdf",
    name: "EnerGulf Business Plan",
    folder: "1. Investment materials",
    documentType: "business_plan",
    evidenceCategory: "commercial_and_financial",
    issuer: "EnerGulf",
    version: "Drive source, September 2025",
    visibility: "restricted",
    reviewNote: "Project-specific business plan. Forecasts, financing requirements, licence status and transaction authority require current source-level review before investor reliance.",
  },
  {
    listingId: "energulf-lotshi-block",
    sourceRef: "InvestDesco/Energulf/COMITE SUIVI PRESENTATION DES RESULTATS DES TRAVAUX ENERGULF 2015 (1).pptx",
    name: "EnerGulf Historical Work Results",
    folder: "2. Technical and geology",
    documentType: "technical_presentation",
    evidenceCategory: "technical",
    issuer: "EnerGulf",
    sourceDate: "2015-01-01",
    version: "2015",
    language: "fr",
    visibility: "restricted",
    reviewNote: "Historical results require reconciliation with current licence and technical status.",
  },
  {
    listingId: "energulf-lotshi-block",
    sourceRef: "InvestDesco/Energulf/energulf_drc_investor_presentation_20251215091416.pdf",
    name: "EnerGulf DRC Investor Presentation",
    folder: "1. Investment materials",
    documentType: "investor_deck",
    evidenceCategory: "commercial_and_financial",
    issuer: "EnerGulf",
    sourceDate: "2025-12-15",
    version: "2025-12-15",
    visibility: "restricted",
    reviewNote: "Current transaction authority, licence status and financing requirement are not independently verified.",
  },
  {
    listingId: "energulf-lotshi-block",
    sourceRef: "InvestDesco/Energulf/contrat_rdc_energulf_cohydro (2).pdf",
    name: "EnerGulf–Cohydro Contract",
    folder: "3. Legal, title and permits",
    documentType: "contract",
    evidenceCategory: "title_and_transaction_authority",
    issuer: "EnerGulf / Cohydro",
    language: "fr",
    visibility: "restricted",
    reviewNote: "Current validity, rights, obligations and approvals require legal review.",
  },
  {
    listingId: "energulf-lotshi-block",
    sourceRef: "InvestDesco/Energulf/CONVENTION_DE_CESSION_DES_PARTS_SOCIALES_Mars (2).pdf",
    name: "EnerGulf Share Transfer Convention",
    folder: "3. Legal, title and permits",
    documentType: "share_transfer_agreement",
    evidenceCategory: "ownership_and_control",
    issuer: "Transaction parties",
    language: "fr",
    visibility: "restricted",
    reviewNote: "Execution, completion, approvals and current ownership require legal confirmation.",
  },
];

export function documentSourcesFor(listingId: string) {
  return projectDocumentSources.filter((source) => source.listingId === listingId);
}
